### ISSUE TITLE
Informe

### ISSUE THREAD

**Issue by NailsDark** [INS125/Laboratorio#10]
Hola, estoy haciendo la tarea usando como base en el diagrama UML y me salió una duda. ¿Qué esta devolviendo el parámetro "informe"? en el enunciado no sale nada sobre eso asi que no estoy seguro que hace exactamente esa funcion.

**Comment by Hormash** [comment]
Hola, ese metodo de la clase usuario es la encargada de crear el archivo .txt con el identificador usuario que contiene la información sobre su planificación y el tiempo trabajado.
