### ISSUE TITLE
Crear Repl

### ISSUE THREAD

**Issue by NaxF11** [INS125/Laboratorio#10]
Profe cuando recibo la invitación para mi repositorio en github, aparece en github, pero en repl cuando me dirijo a : import from github y pongo el link de mi repositorio, me dice que no se puede, solo me aparece los repositorios anteriores, no el de ahora :(

**Comment by matgreco** [comment]
no se hace con "import from github". Debes seguir los pasos que hemos visto en las tres clases anteriores. 

git clone URLREPO

En esta carpeta hay un ayudamemoria de los comandos basicos de git y en el pdf de esa misma carpeta puedes ver los pasos al detalle

https://github.com/INS125/Laboratorio/tree/master/01

Debes seguir lo mismo que hiciste para subir el laboratorio0
