### ISSUE TITLE
Lectura de grafo

### ISSUE THREAD

**Issue by valeuwu** [INS125/Laboratorio#100]
Profe, me entro una dude bien tonta xD, no se en que orden leer la matriz para tener un resultado de acuerdo a lo que pide. Ya que en la clase usted leyó el 0,0 desde la esquina inferior izquierda, pero después me fijé que en otras clases la hemos leído de esta forma:

0,0 | 0,1 | 0,2 | 0,3
1,0 | 1,1 | 1,2 | 1,3
2,0 | 2,1 | 2,2 | 2,3
3,0 | 3,1 | 3,2 | 3,3

o esto no importa?? es que si lo leemos de esta forma el 1,1 pasa a ser obstáculo en el caso 4a, pero como se leyó en la clase es una espacio en blanco

**Comment by matgreco** [comment]
Hola @valeuwu 
Utilicemos las coordenadas cartesianas. Es decir, el nodo(0,0) está en la esquina inferior izquierda. 
En otras aplicaciones (como en computación grafica, o GUI) se toma el 0,0 en la esquina superior izquierda, pero por esta vez utilicemos el 0,0 abajo a la izquierda.

**Comment by valeuwu** [comment]
ya profe, muchas gracias :)
