### ISSUE TITLE
Consulta de grafo

### ISSUE THREAD

**Issue by katherin5928** [INS125/Laboratorio#101]
Profe consulta el grafo tiene que ser relacionado a los dos mundos indicado en el pdf o sea matriz de 3×3 y 6×6 es que me surgió esa duda,ya que estaba leyendo y salía en una parte que en el github saldrían archivos de prueba y eso me confundió .

Por otro lado se puede ocupar matrices para representar los grafos de los mundos, cierto?

**Comment by matgreco** [comment]
Hola @katherin5928,
Si, al crear su repositorio se crearán tres archivos

- mundoA.pl: donde define los hechos del mundo A.
- mundoB.pl: donde define los hechos del mundo B.
- main.pl: donde define las reglas.

Las conexiones entre nodos (el grafo) debe representarlo utilizando el functor conexion. 

`conexion(nodo(0,0), nodo(0,1))`

En el archivo base hay mas ejemplos.
Saludos.

**Comment by katherin5928** [comment]
ahora comprendo, muchas gracias profe.
Profe consulta los  obstáculos los describimos como nodos  en nuestro mundoA y mundoB o no? es que no se si por ser obstáculos son nodos o no. Es que según yo no pero igual estoy en duda
