### ISSUE TITLE
Consulta de archivos 

### ISSUE THREAD

**Issue by katherin5928** [INS125/Laboratorio#102]
Profe cree recién mi repositorio pero hay que trabajar solo en el main.pl o tambien en los otros archivos. 

Y si se tiene que trabajar en lo otros archivos mi consulta es a que se refiere con que tenemos que decir "agregar los hechos del mundo que define...".
Es que no entendí a que se referia a agregar los hechos no se si hay que agregar las conexiones u otra cosa, es que no entiendo muy bien.

**Comment by matgreco** [comment]
Al crear su repositorio, le aparecerán tres archivos los cuales usted debe completar:

    mundoA.pl: Con los hechos del mundo A. Aquí usted defina las conexiones de los nodos de la grilla de 4x4
    mundoB.pl: Con los hechos del mundo B. Aquí usted defina las conexiones de los nodos de la grilla de 6x6
    main.pl: Con las reglas y procedimientos que rigen tanto en el mundo A como mundo B. Es decir, las reglas que describa deben funcionar en ambos mundos.

Un hecho es un functor que define que algo es verdad en ese mundo. En el ejemplo que dimos en la clase, los hechos serían

padre(juan, jose). % juan es padre de jose.

En esta tarea, los hechos son las conexiones.
