### ISSUE TITLE
confucion de datos de los mundo

### ISSUE THREAD

**Issue by katherin5928** [INS125/Laboratorio#103]
profe estaba realizando el lab y en la función acciones_posible me mezcla el mundo a y b.

Por ende si pone que me imprima los movimiento de NODO me lo responde de acuerdo al mundo a y b juntos

ejemplo puse los movimiento de acuerdo a cada nodo y me sale esto:

Las acciones posibles del nodo nodo(0,3) son:                                                                                                
nodo(1,3)nodo(0,2)nodo(0,4)nodo(1,3)nodo(0,2)  

siendo que debería salir nodo(1,3)nodo(0,2). Cuando tenia el mundo A solo me salia bien pero ahora que tengo el mundo b me los mezcla, a que se debe eso?

**Comment by Deivid45-droid** [comment]
Debe ser porque llamas a ambos mundos al mismo tiempo se supone que debes llamar al mundo a y luego al mundo b por separado para evitar ese tema lo mencionaron en la mañana.

**Comment by matgreco** [comment]
si, como dice @Deivid45-droid debes comentar el include correspondiente al otro mundo con `%`

**Comment by katherin5928** [comment]
Y profe consulta en la función camino  uno puede agregar otro parámetro o no?
