### ISSUE TITLE
Consulta sobre Estructura 

### ISSUE THREAD

**Issue by lvp1890** [INS125/Laboratorio#104]
Hola, tengo una duda sobre lo siguiente :
Luego del include viene el main donde se tiene resolvermundoA y resolvermundoB. Esto que es? Porque luego de esto vienen dos funciones, la de los caminos y posibles acciones entonces yo lo que hice ahora fue:
 //aqui tengo el include
//tengo el main y dentro llamo a mi funcion
todas_acciones_posibles(nodo(0,0)) //le paso un nodo a la funcion
halt.

//funcion
y aqui escribo mi funcion pero esto no me funciona si tengo 

resolvermundoA:-
       todas_acciones_posibles(nodo(0,0))//llamo la funcion 
       
todas_acciones_posibles//aqui al escribo pero me tira erro porque la funcion esta dentro del resolvermundoA que no entiendo que es, si lo elimino funciona pero quiero saber que es o como meter las cosas dentro para que funcione sin eliminar la linea

**Comment by Deivid45-droid** [comment]
se supone que en resolver_mundoA tu llamas a las "funciones" que son las reglas acciones_posible y camino del mundo A (no llames a ambos include al mismo tiempo llama a mundoA y luego prueba a mundoB ) y luego llamas a ambas pero en una sola linea en el main.  es como meter 2 funciones en una y llamarlas en el main.

**Comment by matgreco** [comment]
Aqui tambien aparece el ejemplo:

https://github.com/INS125/Laboratorio/tree/master/09
