### ISSUE TITLE
Pregunta nodo

### ISSUE THREAD

**Issue by frago3** [INS125/Laboratorio#105]
Hola,

Si represento la grilla como un grafo, el objetivo es establecer un camino entre A y B?
es necesario establecer todos los caminos posibles?

eso se hace en la parte del main.pl cierto?

no entiendo muy bien lo que hace en esta parte
		acciones_posibles(nodo(X,X)), 
		camino(nodo(X,X), nodo(X,X)).

acciones_posibles debe recibir un solo nodo?

**Comment by Deivid45-droid** [comment]
se supone que debes cambiar (X,X) por (0,3) por ejemplo y te debe dar los movimientos posibles de ese nodo ya sea a la izquierda,derecha,arriba o abajo si tomas  (0,3) conectaría con (0,2) y con (1,3)

**Comment by frago3** [comment]
ahh ok, entonces acciones_posibles(  ) debe recorrer todos los nodos que describen el escenario en mundoA.pl o no?

**Comment by matgreco** [comment]
Hola @frago3, en acciones posibles se recibe un nodo (que lo puedes considerar como la posición en la que está el robot) y te debe retornar las acciones posibles desde ese nodo.

Por ejemplo

`acciones_posibles(nodo(0,0) ).`

Debe responder: 
Las acciones posibles del nodo(0,0) son: nodo(1,0), nodo(0,1)

**Comment by frago3** [comment]
ok, entonces no es necesario que reciba todos los nodos, solo donde se ubica el robot.
o sea la función debe ser llamada de la función camino cierto?
