### ISSUE TITLE
Resultado

### ISSUE THREAD

**Issue by blpezsandoval** [INS125/Laboratorio#106]
Cual es la forma que debe mostrar el programa al finalizar?

Forma 1:
Las acciones posibles del nodo nodo(0,3) son: nodo(1,3), nodo(0,2),                                                                                                                                
moverse al nodo(1,3)                                                                                                                                                                               
Las acciones posibles del nodo nodo(1,3) son: nodo(2,3), nodo(0,3),                                                                                                                                          
moverse al nodo(2,3)
etc...

Forma 2:
Las acciones posibles del nodo nodo(0,3) son: nodo(1,3), nodo(0,2),                                                                                                                                
moverse al nodo(1,3)                                                                                                                                                                               
moverse al nodo(2,3) 
etc...

**Comment by Deivid45-droid** [comment]
se supone que debe ser las acciones posibles de nodo(0,3) son: nodo(1,3),nodo(0,2) como lo dice el comentario en acciones posibles según lo que yo entendí.

**Comment by matgreco** [comment]
forma 2

**Comment by blpezsandoval** [comment]
Gracias
