### ISSUE TITLE
condicionales en prolog 

### ISSUE THREAD

**Issue by Deivid45-droid** [INS125/Laboratorio#107]
Podrían explicar un poco de como hacer condicionales? es que creo que no entendí correctamente esta parte de como poder escribir "bien" un condicional que necesito y tengo pensado aplicar pero se me dificulta el como hacerlo.

**Comment by Joaquin-Cortes** [comment]
https://us-lti.bbcollab.com/collab/ui/session/playback en esta ayudantia explican un poco las condicionales bro en el min 30

**Comment by Deivid45-droid** [comment]
vale vale muchas gracias

**Comment by Joaquin-Cortes** [comment]
https://swish.swi-prolog.org/p/Tutorial%20de%20prolog.swinb en el punto 4 puede que sirva

**Comment by matgreco** [comment]
Aqui tambien aparece el ejemplo:

https://github.com/INS125/Laboratorio/tree/master/09
