### ISSUE TITLE
Error con Mundo A

### ISSUE THREAD

**Issue by Erick-Peralta** [INS125/Laboratorio#108]
Hola, 

1) estoy viendo el codigo inicial que viene en el archivo del Mundo A y trae lo siguiente:

estado_inicial(nodo(0,3)). % estado inicial describe el nodo donde inicia el agente
estado_objetivo(nodo(3,0)) % estado objetivo describe el nodo donde el agente debe llegar.

Efectivamente si nos guiamos por un plano cartesiano o de coordenadas, el punto rojo estaría en el punto 0,3 sin embargo el punto azul (objetivo) estaría segun yo en el punto 2,0 y no en el punto 3,0 como viene por defecto.

https://subefotos.com/ver/?0aa3871120827a799766cfd46ab13a4fo.png

Habría que arreglar eso? 

2) Para el Mundo B, el 0,0 también estaría en la misma posicicón que del mundo A, es decir Fila 6 Columna 1?  si ese fuese el caso entonces el punto azul estaría en el punto 3.0?

Saludos

**Comment by Deivid45-droid** [comment]
en el mundo A si es el nodo(2,0) pero eso es independiente ellos después cambiaran esos nodos al revisar (ocupalo como te acomode  )y si  ambos se toman como que el nodo(0,0) es el nodo inferior izquierdo.

**Comment by matgreco** [comment]
Tal como dice @Deivid45-droid , lo que sale ahi es solo un ejemplo. Guíese por lo indicado en el enunciado.
