### ISSUE TITLE
Dudas de ir recorriendo los espacios

### ISSUE THREAD

**Issue by NaxF11** [INS125/Laboratorio#109]
1.- En camino(NODO_INICIAL, NODO_OBJETIVO), tengo entendido que ud mencionó que hay que usar recursividad, lo cual lo implementé y la consola me arroja por ej:

Tomando la primera figura:
 Parte desde el nodo 3,0 , entonces puede moverse a 1,3 o a 0,2, si mi programa escoge la posición 1,3 entonces aplico recursividad y luego volverá a preguntar dónde puede moverse desde 1,3 que sería 3,0 (por donde ya paso) o 2,3. Entonces no entiendo cómo hacer que no pase por el mismo camino, ya que implementando esto como dije estaría en un bucle infinito (Vade 3,0 a 1,3 luego de 1,3 a 3,0).

2.- Por lo que tengo entendido acciones_posibles debe ir imprimiendo cada espacio que vaya recorriendo el nodo? O solamente ese ejecuta una vez imprimiendo las acciones posibles de la primera posición (0,3)?

3.- El tema de usar el else ( ; ) siempre me arroja error al usarlo , no lo tengo bien entendido.

**Comment by Deivid45-droid** [comment]
se supone que el ; es un or según tengo entendido no un else,  por otro lado se supone que las acciones posibles son los movimientos que se pueden hacer desde un solo nodo en especifico arriba,abajo,izquierda, derecha. 
Me pasa lo mismo porque se supone que con recursividad  uno llama al nodo padre de ese nodo pero uno esta diciendo que hay una relación padre hijo en ambos sentidos por lo cual tira un bucle yo lo solucione tomando una sola opción no las 2 nodo(0,0) ,nodo(0,1) y nodo(0,1) ,nodo(0,0)(que permite realizar un camino pero no entrega todas las acciones posible de un nodo porque no se le esta dando conexión como lo tome yo) se debería ocupar el ; diciendo (nodo_padre,nodo_hijo) or (nodo_hijo,nodo_padre según la dirección de la conexión ).
:- --> Es equivalente "Si" o "si".
, --> Es equivalente "AND".
; --> Es equivalente a "OR"

**Comment by matgreco** [comment]
1.- Para que no visite la misma posición (que ya está visitada) y se quede en un bucle infinito, se pude usar una liista en la cual ir guardando los estados visitados. Se va a subir un instructivo sencillo sobre como usar listas.

2.- Las acciones posibles entrega las posiciones que se puede visitar desde UN NODO. 

3.- En el readme de la carpeta 9 hay un ejemplo como usar el or en un condicional ( condicion -> TRUE ; FALSE )

**Comment by Erick-Peralta** [comment]
> 1.- Para que no visite la misma posición (que ya está visitada) y se quede en un bucle infinito, se pude usar una liista en la cual ir guardando los estados visitados. Se va a subir un instructivo sencillo sobre como usar listas.
> 
> 2.- Las acciones posibles entrega las posiciones que se puede visitar desde UN NODO.
> 
> 3.- En el readme de la carpeta 9 hay un ejemplo como usar el or en un condicional ( condicion -> TRUE ; FALSE )

Profe una pregunta, resulta que no se si habré llegado al mismo punto del bucle infinito pero mi programa me arroja lo siguiente **(teniendo en cuenta que mi punto de partida es el nodo 0,3 y que posteriormente debería ir al nodo 0,2 y posteriormente al 0,1)**

```
Moverse al nodo (0,2)
Moverse al nodo (0,2)
Moverse al nodo (0,2)
Moverse al nodo (0,2)
Moverse al nodo (0,2)
Moverse al nodo (0,2)
Moverse al nodo (0,2)
Moverse al nodo (0,2)
Moverse al nodo (0,2)
Moverse al nodo (0,2)
Moverse al nodo (0,2)
Moverse al nodo (0,2)
Moverse al nodo (0,2)
Moverse al nodo (0,2)
Moverse al nodo (0,2)
...
```

Habré llegado al mismo bucle infinito al que se refiere mi compañero y solo debo esperar a que suban el instructivo sobre como usar listas para nodos ya visitados (en este caso el 0,2 y que no se vuelva a repetir?)

Muchas gracias

**Comment by matgreco** [comment]
> > 1.- Para que no visite la misma posición (que ya está visitada) y se quede en un bucle infinito, se pude usar una liista en la cual ir guardando los estados visitados. Se va a subir un instructivo sencillo sobre como usar listas.
> > 2.- Las acciones posibles entrega las posiciones que se puede visitar desde UN NODO.
> > 3.- En el readme de la carpeta 9 hay un ejemplo como usar el or en un condicional ( condicion -> TRUE ; FALSE )
> 
> Profe una pregunta, resulta que no se si habré llegado al mismo punto del bucle infinito pero mi programa me arroja lo siguiente **(teniendo en cuenta que mi punto de partida es el nodo 0,3 y que posteriormente debería ir al nodo 0,2 y posteriormente al 0,1)**
> 
> ```
> Moverse al nodo (0,2)
> Moverse al nodo (0,2)
> Moverse al nodo (0,2)
> Moverse al nodo (0,2)
> Moverse al nodo (0,2)
> Moverse al nodo (0,2)
> Moverse al nodo (0,2)
> Moverse al nodo (0,2)
> Moverse al nodo (0,2)
> Moverse al nodo (0,2)
> Moverse al nodo (0,2)
> Moverse al nodo (0,2)
> Moverse al nodo (0,2)
> Moverse al nodo (0,2)
> Moverse al nodo (0,2)
> ...
> ```
> 
> Habré llegado al mismo bucle infinito al que se refiere mi compañero y solo debo esperar a que suban el instructivo sobre como usar listas para nodos ya visitados (en este caso el 0,2 y que no se vuelva a repetir?)
> 
> Muchas gracias

No, eso claramente es que estás haciendo mal la recursividad. 

Dentro de la recursividad debes llamar a la funcion de manera recursiva pero desde la nueva posicion.
