### ISSUE TITLE
Año marcas

### ISSUE THREAD

**Issue by bryanrodrguez** [INS125/Laboratorio#11]
Hola , estaba revisando los datos entregados en marcas y me di cuenta que en año marcas es "2020" y en el output me tiraba todo false ya que el año planificacion es "2021", por si es un error de tipeo en el txt o debe ser asi , ya que con el año 2021 en marcas funciona como el ejemplo entregado

**Comment by Hormash** [comment]
son del año 2021, fue un error mio
