### ISSUE TITLE
consulta con funciones

### ISSUE THREAD

**Issue by katherin5928** [INS125/Laboratorio#11]
profe es necesario tener en una función de la producción del hash o puedo tenerlo directo main.
@matgreco

**Comment by matgreco** [comment]
No es necesario, ni tampoco será evaluado. Puede tenerlo todo dentro del main si así lo prefiere, pero hacer una función le ayudará mucho a entender su código, depurarlo, y definir una función es muy sencillo por lo que no debería ser algo dificultoso.
Pero queda a decisión suya.

Saludos.

**Comment by katherin5928** [comment]
profe sabe que hice lo de generar archivo pero como mi dev c no me funciona muy bien porque tengo window lo intente en Repl.it y para eso utilice 

FILE *salida;
	salida = fopen("salida.txt", "w");

pero sin embargo no me crea el archivo en Repl.it y no se porque  :/
bueno al parecer si me lo crea porque ocupe una sentencia 


if (salida==NULL){
   	perror("ERROR EN LA APERTURA DE ARCHIVO");
		return 1;
 }

y no me muestra el NULL pero lo raro es que no me parece como creado y no se porque si luego para agregarle las cosas al archivo ocupe un : 

 fprintf(salida,"%i" ,pala[i]);

que me debería imprimir en el archivo de texto.

@matgreco

**Comment by katherin5928** [comment]
ahh.... y otra cosa es que utilice mi código con el primer archivo de entrada y funciono super bien sin embargo al hacer con el segundo ejemplo no funciono muy bien, por lo tanto pensé que era mi código e intente de hacerlo con su código principal solo sin mis modificaciones y tirandole el archivo entrada.txt del segundo ejemplo. sin embargo igual me tiro error no entiendo porque?

ademas que ocupe mi código con distintas palabras y me funcionaba bien . Solo que con el segundo ejemplo no se que paso.

Por si acaso lo estoy haciendo por Repl

**Comment by matgreco** [comment]
@katherin5928, el archivo parece ser abierto correctamente para escritura y tu dices que lo crea. De acuerdo a lo que logro interpretar, es que no escribe cosas en el archivo o lo escribe de manera incorrecta. Probé tu código y me funcionó, solo le cambié la mascara. Tienes una máscara de entero y te estará escribiendo el valor correspondiente al codigo ascii de la letra en pala[i].  

Tambien fíjate que tienes un return 1 si es que sucede un error. Si  tienes código luego de ese return no se ejecutará.

Respecto a la otra pregunta, dime cual fue el error y podemos verlo.

**Comment by katherin5928** [comment]
profe sabe me sale como el error un "exited segmentation fault" y no se a que se debe eso, ya que en lo provee con el primer ejemplo y la salida correctamente sin embargo igual me tira"exited segmentation fault"

**Comment by matgreco** [comment]
Eso es porque el arreglo que contiene la linea tiene tamaño 255.

Reemplaza la linea 8. Donde dice:
```
  char linea[255];
```
Debe decir:

```
  char linea[5000];
```

El 5000 significa que puede guardar una linea de 5000 caracteres.

Eso provocó un cambio en el código base. Actualizamos ahora

**Comment by katherin5928** [comment]
a ya gracias profe

**Comment by katherin5928** [comment]
pero profe en la salida del segundo ejemplo no se imprime la salida en la del primer ejemplo si pero la del segundo ejemplo no, a que se debe eso

@matgreco

**Comment by katherin5928** [comment]
es que si cambio el numero de primer while a 5000 en el rsultado de la linea 6 me da 
-2147483648  |    37  
y deberia dar otra cosa en esa linea

**Comment by matgreco** [comment]
eso tiene que ver con el tipo de dato. No se exactamente que representan tus números, pero te recomendaria usar tipos de datos sin signo

**Comment by katherin5928** [comment]
como sin signos?? es que mis arreglos representan los codigos ascii y las veces que se repiten

@matgreco

**Comment by katherin5928** [comment]
profe entiendo que el tipo de dato pero me dice que ocupo signo y según yo no ocupo signos pues ocupo puras variables de tipo entero, en calculo el cual me tira el error pues en ascii me los calcula todo bien

**Comment by katherin5928** [comment]
gracias
