### ISSUE TITLE
Clase del 4 de junio 

### ISSUE THREAD

**Issue by nicolasGallegos** [INS125/Laboratorio#110]
Alguien puede mandar el link de la ayudantia del jueves 4 de junio por favor

**Comment by frago3** [comment]
acá hay una ayudantía de hoy :
https://us.bbcollab.com/collab/ui/session/playback/load/fefadf9c4aa74dee8d06cff57fd899d8

**Comment by matgreco** [comment]
Hola, ya se agregó a la planificación.
