### ISSUE TITLE
Pregunta, acciones_posibles

### ISSUE THREAD

**Issue by Erick-Peralta** [INS125/Laboratorio#111]
Hola, quiero saber si entendí bien esta regla: por lo que entendí, dentro del procedimiento resolver_mundoA está la regla accciones_posibles(nodo(X,X)) es decir que ahí debo reemplazar la posición o nodo en donde se encontrará inicialmente "el robot" o el punto rojo que está en la figura 4A (0,3)?

2) Por otra parte mas abajo del main está la regla en cuestión el cual dice que deberá imprimir las opciones posibles para moverse de un nodo a otro (por ejemplo que muestre que el nodo (0,0) tiene las opciones para moverse en el nodo(0,1) o (1,0). Ahora esto tengo que relacionarlo directamente  con el "include" del mundo A donde se ponen las conexiones(nodo(0,0), nodo (0,1)) conexiones(nodo(0,0), nodo(1,0)) esto último se ocupa para esta regla de acciones_posibles? O se ocupa para la regla camino(NODO_INICIAL, NODO_OBJETIVO)?

3) Dado que esta última regla de camino(NODO_INICIAL, NODO_OBJETIVO) tiene la misma estructura que los hechos que tenemos que definir en los include de los mundo conexiones(nodo(0,0),nodo(0,1)) me salta la confusión acaso son exactamente lo mismo o no? 

Saludos

**Comment by matgreco** [comment]
1.- Si, es correcto. acciones_posibles del estado inicial.
2.- Para ambas, usted al agregar el include mundoA, le entrega el mapa del mundo. La regla acciones_posibles y camino deben funcionar en cualquier mundo.
3.- camino debe ir imprimiendo el camino que toma para ir desde un nodo a otro, uno a uno. No es lo mismo que conexion.
