### ISSUE TITLE
acciones posables

### ISSUE THREAD

**Issue by frago3** [INS125/Laboratorio#112]
respecto a las acciones posibles de un nodo, ¿Cómo debe imprimir los datos?

En el ejemplo aparece lo siguiente:
% estructure su programa para que imprima de la forma: Nodo(0,0), Nodo(1,1), Nodo(2,2)

eso quiere decir que el Nodo(0,0) se puede mover al Nodo(1,1) y Nodo(2,2)??

A la función acciones posibles hay que enviarle cada nodo del mundo cierto? 
eso hay que decláralo en la parte que dice "resolver_mundoA "?  de declara cada nodo a evaluar ahí  no?
que pasa si un nodo no tiene acciones posibles?

**Comment by SebastianGonzalez777** [comment]
Según lo que tengo entendido yo, en acciones posibles debes mostrar los nodos con los que se conectará el nodo inicial. Por ejemplo: si tu nodo inicial es (1,1), y al rededor de ese nodo no hay ningún obstáculo, entonces tienes 4 posibles nodos de conexión; el nodo de arriba-abajo-izquierda-derecha, entonces esos debes mostrar de la forma en que se te pide (Nodo(X,X), Nodo(X,X), Nodo(X,X)). Espero haber ayudado compa

**Comment by frago3** [comment]
si gracias, me queda mas claro. 
estaba complicado porque no entendía como enviar enviarle los nodos del mundo a la función, ahora se que existe el "forall( :Cond, :Action )"

**Comment by matgreco** [comment]
Basta con utilizar solo el nodo del estado inicial para las acciones posibles. Sin embargo, la regla debe generalizar para cualquier nodo

La salida debe ser

Las acciones posibles del nodo(10,10) son: nodo(9,10), nodo(10,9)
