### ISSUE TITLE
Pregunta acciones_posibles

### ISSUE THREAD

**Issue by matixzz9** [INS125/Laboratorio#113]
Hola, tengo una duda con el archivo main, resulta que en el procedimiento resolver_mundoA reemplacé las "X" y borré el otro procedimiento de camino, para centrarme primeramente en el primer procedimiento. Resulta que me quedó de la siguiente forma:

resolver_mundoA :-
		acciones_posibles(nodo(0,0)). % Describa el estado inicial definido en el enunciado

Lo que hice fue colocar la coordenada de un nodo, en este caso la coordenada del nodo incial (0,0)
luego en la regla puse mi codigo, lo cual creo que me funcionó puesto que por consola me imprime lo siguiente:

Las acciones posibles del nodo(0,0) son:                                                                                                             
nodo(0,1)                                                                                                                                            
nodo(1,0)

Y es aqui donde tengo la duda, ¿Como será la forma de evaluar? En mi procedimiento resolver_mundoA, ¿tengo que poner todos los nodos yo mismo? es decir quedándome así:

resolver_mundoA :-
		acciones_posibles(nodo(0,0)). 
		acciones_posibles(nodo(0,1)),
		acciones_posibles(nodo(0,2)), 
		acciones_posibles(nodo(0,3)), 
		acciones_posibles(nodo(1,0)). 
                .....
¿o no? no entiendo muy bien esa parte, o donde la forma de evaluar será automática, ¿no es necesario colocar las coordenadas de todos los nodos en el procedimiento resolver_mundoA?

**Comment by panchocorderos** [comment]
Hola @matixzz9 , dos cosas:
1. La forma de imprimir en acciones_posibles es la siguiente: % estructure su programa para que imprima de la forma: Nodo(0,0), Nodo(1,1), Nodo(2,2).
O sea en tu caso deberia imprimir:
Las acciones posibles del nodo(0,0) son: nodo(0,1), nodo(1,0)

2. Según lo que explicó el profesor en clases, ellos pondrán un nodo, no es necesario probarlo con todos.

Saludos!

**Comment by matgreco** [comment]
Lo que @matixzz9 hizo es correcto. Basta con poner el nodo del estado incial en su procedimiento de resolver_mundoX. Pero  esa regla debe generalizar para cualquier mundo y cualquier nodo.

lo que dice @panchocorderos es correcto, gracias!
