### ISSUE TITLE
Pregunta variables

### ISSUE THREAD

**Issue by lvp1890** [INS125/Laboratorio#114]
En la siguientes lineas, debo colocar acciones_posibles(NODO) como una variable o debo dejarlo como esta abajo?

% procedimiento para resolver el mundo A con su estado inicial y objetivo
resolver_mundoA :-
		acciones_posibles(nodo(0,3)), % Describa el estado inicial definido en el enunciado
		camino(nodo(0,3), nodo(2,0)). % Describa el procedimiento para encontrar el camino en el mundo A.

**Comment by matgreco** [comment]
Eso está correcto, si lo prefiere hacer como variable tambien estaría correcto. Eso queda a criterio del programador.

**Comment by lvp1890** [comment]
En esa misma parte del codigo debo igual declarar algo como:
estado_inicial(variable)
estado_final(variable)
o solamente dejo las lineas del comentario anterior?
