### ISSUE TITLE
Pregunta con recursividad

### ISSUE THREAD

**Issue by Erick-Peralta** [INS125/Laboratorio#115]

**Comment by matgreco** [comment]
Estimado @Erick-Peralta , no se si se percató, pero está regalando su tarea. Edité su pregunta.

Respecto a los bucles, le recomiendo agregar los nodos visitados a una lista y verificar que el proximo nodo no esté en la lista de visitados. Puede ver acá como trabajar con listas.

https://github.com/INS125/Laboratorio/tree/master/10
