### ISSUE TITLE
Entrar a cierto indice

### ISSUE THREAD

**Issue by Ronkoi** [INS125/Laboratorio#117]
Buenas, tengo la siguiente duda por si me pueden ayudar.

Me gustaría ingresar a algún elemento de la conexión que tiene cierto nodo, ya que al llamarlo siempre mostrará su primera conexión que está definida, lo intenté con un forall, pero eso simplemente hará el recorrido por todas sus conexiones, no puedo rescatar exactamente la 2da conexión por ejemplo

**Comment by Hormash** [comment]
Desconozco si se puede seleccionar el segundo elemento, la idea es que el conjunto de reglas te permita avanzar por la selección.

De todas maneras puede que no siempre se encuentre la solución al problema.
