### ISSUE TITLE
warning: Goal (directive) failed: user:main 

### ISSUE THREAD

**Issue by bguzmnzrate** [INS125/Laboratorio#118]
1) Al realizar todo el proceso correctamente la consola me arroja la advertencia, **"Goal (directive) failed: user:main "**, puedo dejar el programa con ese warning? (no afecta su rendimiento, XD), o alguien sabe a que se refiere?.

2) Sobre los functores, estado_inicial y estado_objetivo, donde debo ponerlos, ya que al ponerlos en acciones_posibles(estado_inicial) y camino(estado_inicial, estado_objetivos) no me son útiles.

**Comment by matgreco** [comment]
1.- Debe sacarlo, probablemente es porque falta el caso base.
2.- En los archivos de los hechos.
