### ISSUE TITLE
mundos

### ISSUE THREAD

**Issue by frago3** [INS125/Laboratorio#119]
hola, debe resolver ambos mundos simultáneamente?

está permitido si el mundo lo defino de esta manera:

nexo(nodo(4,4), nodo(3,4)).

conexion(X,Y):- nexo(X,Y).
conexion(X,Y):- nexo(Y,X).

**Comment by Hormash** [comment]
Si, usted decide como realizar la conexión bidireccional

**Comment by frago3** [comment]
hola, debe resolver ambos mundos simultáneamente?
es que me da un error si intento resolver los dos al mismo tiempo

**Comment by Hormash** [comment]
No, se evaluara uno a la vez.
