### ISSUE TITLE
Linux + otra cosa

### ISSUE THREAD

**Issue by ssozaprez** [INS125/Laboratorio#12]
Profe, ¿exactamante qué es el Linux en cuanto a este problema? Ya que me aparace como una de las cosas que debo tener para resolverlo. Estoy en Windows 10 y tengo el Dev-C++ instalado. O todo se arma en el repl.it? No entiendo esto. También quisiera preguntar exactamente qué provoca la creación de archivos de entrada y salida.

**Comment by Hormash** [comment]
Hola ssozaprez,

Linux es un sistema operativo de tipo Unix. La tarea será revisada en ese sistema operativo, por lo que se pide que ustedes trabajen en alguna distribución de Linux para no tener problemas.

Si su código lo realiza en Windows 10, pruébelo y compile los archivos, en algún entorno Linux antes de subirlo a la repo final.
Repl.it es una maquina virtual en Ubuntu Linux la cual tiene todo lo necesario para que puedan trabajar sin la necesidad de instalar algo en sus computadores.

Con respecto a los archivos de entrada y salida.

- Archivo de entrada: su código debe ser capaz de leerlo (el código que se encuentra en _main.c_ ya lo realiza). Este tiene un formato definido en el enunciado. (no lo debe crear el programa, pero si puede hacer los suyos a mano)

- Archivo de salida: este debe ser creado por su programa, respetando el formato de este archivo.

No entiendo el "qué provoca". A qué te refieres?

**Comment by ssozaprez** [comment]
Gracias por lo del Linux. ¿Entonces solo con hacerlo en C en repl.it basta?

Por "qué provoca" me refiero a qué exactamente genera los archivos de entrada y salida, ya que el generarlos es una de las exigencias para la tarea. ¿Poner alguna librería al inicio del código o algo así?

**Comment by Hormash** [comment]
Si, con hacerlo en repl.it y si funciona basta.

Como mencione en el comentario anterior. Tu código debe generar un archivo de salida, mientras que el de entrada leerlo. 

Tu código no debe generar un archivo de entrada.

**Comment by ssozaprez** [comment]
¿Entonces un archivo de entrada ya está definido de por sí?

**Comment by Hormash** [comment]
El archivo de entrada ya existe, tu puedes crear uno si quieres a mano. Tiene un formato que se encuentra descrito en el enunciado.

Aquí tienes un ejemplo 
https://github.com/INS125/Laboratorio/blob/master/Tarea1/ejemplo1/entrada.txt
