### ISSUE TITLE
Seleccionar parte del archivo

### ISSUE THREAD

**Issue by NailsDark** [INS125/Laboratorio#12]
Cuando quiero sacar solo una parte del archivo este solo me sale con un digito. Por ejemplo:

with open("Usuarios.txt", 'r') as file_in:
  for line in file_in:
     print(line[0])

me imprime solo el primer digito, cuando quiero imprimir todo lo que hay antes de la coma. ¿Como lo soluciono?

**Comment by Hormash** [comment]
con print(line)
