### ISSUE TITLE
Xs

### ISSUE THREAD

**Issue by ssozaprez** [INS125/Laboratorio#120]
Profe, ¿las Xs de las funciones pre-hechas no se alteran? ¿Ustedes y/o la revisión automática simplemente cambiarán las Xs por números al momento de revisar? ¿Sólo me preocupo de rellenar las reglas?

**Comment by Hormash** [comment]
Nosotros evaluaremos la función de los caminos posibles para un nodo y como puede resolver el camino dado dos nodos. 
La idea no es alterar mucho el código, pero si lo encuentre necesario lo puede realizar.

**Comment by matgreco** [comment]
Creo que se refiere a las X donde dice `nodo(X,X)`.

Si, esas se cambian. Es un ejemplo donde usted debe reemplazar las coordenadas del nodo.

**Comment by ssozaprez** [comment]
Sip, a eso me refería: Las Xs en los argumentos nodo(X,X). Gracias.
