### ISSUE TITLE
Datos de clase a clase

### ISSUE THREAD

**Issue by valeuwu** [INS125/Laboratorio#123]
Profes, como pasamos datos de una clase a la otra sin ser heredado por ejemplo en el caso de Partida a Jugador??, busque en internet pero no hay un resultado que me aclare la pregunta :(.

**Comment by screid** [comment]
Recuerda que en Partida debes iniciar, en el constructor, la lista de jugadores junto a las casillas totales del juego. Por lo tanto, cuando después quieras llamarlos dentro de Partida (una característica particular, por ejemplo la función tirar dado, sería:

j1.tirarDado()

Eso sí, recuerda que debes primero declarar qué es j1, en este caso sería 1 valor de la lista de jugadores, la cual iniciaste dentro del constructor de Partida.

**Comment by valeuwu** [comment]
entonces tendría que guardar la lista de jugadores en una función dentro de la clase para poder crear el objeto en el main??

**Comment by valeuwu** [comment]
Profe pude solucionar este problema, muchas gracias

**Comment by screid** [comment]
Hola Vale,
¿Te refieres que no se entiende bien en el enunciado o que aún no entendiste lo que te dije yo? :(

**Comment by valeuwu** [comment]
es que me costo un poquito porque pensé que esto se podía hacer en una parte especifica del código, pero gracias a su mensaje supe que también se podía hacer dentro de una clase xD, si se entiende lo que me dijo :)

**Comment by screid** [comment]
ahh bkn! :)
