### ISSUE TITLE
consulta de funcion Partida

### ISSUE THREAD

**Issue by katherin5928** [INS125/Laboratorio#124]
Profe consulta en la clase Partida la lectura del archivo tiene que ser en init? es que según yo en Partida init no recibe nada, pero si tengo que leer el archivo,  tiene que recibir el nombre del archivo para acceder a los datos.Por otro lado para la lectura del archivo podemos crear otra función o solo tenemos que trabajar con las funciones que se nombran en el diagrama tales como elegirJugador(),jugador(),accionCasilla(),etc

**Comment by screid** [comment]
Katherine, recuerda que en partida, en el init (es decir, en el constructor), debes poner como objetos a la lista de atributos y las casillas.

te recomiendo que en la lectura del archivo trabajes con las funciones del diagrama, las que pusiste tú ahí.

**Comment by katherin5928** [comment]
Pero no comprendo eso pues en el main sale que la "juego("entrada.txt")", lo cual significa que en la clase init recibirá  ese parámetro, sin embargo en el diagrama de clase sale que no recibe ninguno.Por otro lado si o si tengo que recibir el nombre como para metro sin embargo ninguna función la recibe algún parámetro en mi clase Partida.  Entonces tengo esa confucion con la lectura :(

**Comment by screid** [comment]
Ahhh Ok. Te lo explico en más detalle a ver si se entendío:

- En la clase init (el constructor), debe recibir la lista de jugadores y las celdas del juego, nada más.
- Dentro la clase Partida debes crear un método de lectura, el cual debe ser capaz de leer la entrada que les pusimos nosotros (el .txt de entrada, el cual tenía la cantidad de jugadores, sus nombres, etc.).

Se entendió mejor ahí??

**Comment by katherin5928** [comment]
Si, ahora entendí gracias

**Comment by kathy-23** [comment]
¿jugador se lo paso por parámetro a Partida? por que jugadores tiene los atributos de la clase jugador, pero no entiendo como indicarlo, o si esta implícito. Ademas en elegir jugador la lista de Turnos corresponde a una lista de jugadores que puedo heredar del atributo turnos?

**Comment by screid** [comment]
Sí, la lista de jugadores debes pasarle en el constructor a la clase Partida. Cuando los llamas, deberían guardarte toda la info desde Jugador (nombre, ficha, etc).

En cuanto a la función turno(), esta me devuelve una lista de jugadores en el orden deseado y, como están dentro de la misma clase, puedes llamarlo en simulación()
