### ISSUE TITLE
Consulta SEED

### ISSUE THREAD

**Issue by panchocorderos** [INS125/Laboratorio#125]
En el formato de entrada.txt en la primera linea tenemos los siguientes datos:

"N jugadores X celdas SEED Costo propiedades Costo fianza Dinero Inicial"

Mi pregunta es para que se utilizaría el dato SEED, que no entendí muy bien la explicación del pdf.
Saludos!

**Comment by nicolasGallegos** [comment]
Se usa para el random, para q los randit con la misma seed te de los mismos resultados.

**Comment by screid** [comment]
Muchas gracias nicolas! Como decía tu compañero anteriormente, es para darle un valor a la semilla :) acuerdate que si no le colocas ese valor, cada vez que lo corras te darán resultados distintos.
