### ISSUE TITLE
Duda constructor __init__

### ISSUE THREAD

**Issue by NaxF11** [INS125/Laboratorio#127]
la función __init__ se que es el constructor de una clase, pero estoy un poco confundido, en el diagrama aparece solamente __init__ en la clase Partida(), pero en el resto de las clases no, entonces solamente debería poner dicha  función  en esa clase nomas?

**Comment by screid** [comment]
Si bien deben crear un constructor en el método Partida, sí les recomiendo que realicen el constructor también para todas las clases (al menos así lo hice yo). Como que nunca está de más.
