### ISSUE TITLE
composición o agregación

### ISSUE THREAD

**Issue by katherin5928** [INS125/Laboratorio#128]
Profe  sabe que estaba viendo el diagrama de clase  de la tarea y observe que las flechita de Partida recibe a Jugador por agregación, ya que el rombo de color blanco es agregación. Sin embargo en el pdf cuando uno lee la primera pagina en la penúltima linea sale en cursiva que tiene que ser composición, por ende mi duda es sobre como lo hago si con composición o agregación.

**Comment by screid** [comment]
Hola Katherin!

Tienes toda la razón, ahora mismo lo arreglo y se los vuelvo a subir de manera corregida. Es una composición como decías tu :)

**Comment by matgreco** [comment]
Hola @katherin5928 , muy buena observación. El diagrama tiene ese error, ya que lo que se busca es que programen esas clases con una composición.

Les recuerdo que en una composición, al destruir un objeto de la clase que se compone de otra, tambien se destruye esa. Es decir, una vez que se destruya la clase partida, tambien se destruiran los objetos de la clase jugador, propiedad y carcel asociados al objeto tipo partida.

Para lograr ese comportamiento, el objeto jugador, propiedad o carcel debe ser instanciado dentro del constructor de la clase Partida.

**Comment by matgreco** [comment]
Listo, fue corregido y agregado aquí https://github.com/INS125/Laboratorio/tree/master/Tarea5

Muchas gracias @katherin5928 por la observación.
