### ISSUE TITLE
Valores randomizados no son iguales al ejemplo (Después de setear la semilla)

### ISSUE THREAD

**Issue by alegrimminck** [INS125/Laboratorio#129]
Luego de usar la semilla del texto de entrada en random.seed() comprobé que los métodos de random siempre me entregaran los mismos resultados y así ocurrió (Dejó de usar la hora de mi computador para el random). El problema está en que no son los mismos resultados presentados en el ejemplo entrada-salida que nos entregaron, para randomizar el dado usé random.randint() y para randomizar las celdas use random.choice(). Tal vez la versión de Python afectará el cálculo de random? 

DATOS ADICIONALES:

Mi versión de Python: 3.6.9

Comprobé que se gastara lo dicho en el archivo de entrada para la compra de propiedad
y el pago de fianza, también corroboré que el orden de los jugadores fuera el correcto y que se terminara su juego una vez no pudieran pagar la fianza o la propiedad.

-Cálculo del número del dado: random.randint(1,6)
-Cárcel o propiedad: random.choice( ["Propiedad","Carcel"] )
     Orden de celdas: propiedad, propiedad, carcel, propiedad, carcel, carcel.

ARCHIVO DE ENTRADA:

4 6 1 3000 5000 10000
Samantha Gato
Matias Perro
Marco Sombrero
Nicolas Pelota

ARCHIVO DE SALIDA:

Samantha 1 4 4 Propiedad 7000
Matias 1 6 6 Carcel 5000
Marco 1 4 4 Propiedad 7000
Nicolas 1 2 2 Propiedad 7000
Samantha 2 1 5 Carcel 2000
Matias 2 4 FinJuego
Marco 2 1 5 Carcel 2000
Nicolas 2 4 6 Carcel 2000
Samantha 3 4 FinJuego
Marco 3 5 FinJuego
Nicolas 3 1 FinJuego

El ganador aún no lo programo pero no debería afectar según mi problema.

**Comment by Joaquin-Cortes** [comment]
https://www.analyticslane.com/2019/02/11/fijar-la-semilla-de-numeros-aleatorios-en-python/ aca sale como poner una semilla al random espero que te sirva

**Comment by alegrimminck** [comment]
> https://www.analyticslane.com/2019/02/11/fijar-la-semilla-de-numeros-aleatorios-en-python/ aca sale como poner una semilla al random espero que te sirva

Gracias por la info pero como aclaré en mi problema eso ya lo tengo resuelto y si logré darle la semilla al random.

**Comment by javonunezz** [comment]
A mi igual me tira que Matías parte en cárcel y no en propiedad

**Comment by JulioFe** [comment]
A tambien me da diferente

Samantha 1 4 4 Propiedad 7000 
Matias 1 6 6 Carcel 5000 
Marco 1 4 4 Propiedad 7000 
Nicolas 1 2 2 Propiedad 7000 
Samantha 2 1 5 Carcel 2000 
Matias 2 4 Fin Juego
Marco 2 1 5 Carcel 2000 
Nicolas 2 4 6 Carcel 2000 
Samantha 3 4 Fin Juego
Marco 3 1 Fin Juego
Nicolas 3 6 Fin Juego
Ganador Matias

**Comment by screid** [comment]
Hola!

No se preocupen tanto por tener el mismo orden en el ejemplo, la idea es que sepan ocupar bien la función seed que, tal como mencionaron arriba, sólo nos servirá para setear una semilla.

**Comment by tomas-e** [comment]
> A tambien me da diferente
> 
> Samantha 1 4 4 Propiedad 7000
> Matias 1 6 6 Carcel 5000
> Marco 1 4 4 Propiedad 7000
> Nicolas 1 2 2 Propiedad 7000
> Samantha 2 1 5 Carcel 2000
> Matias 2 4 Fin Juego
> Marco 2 1 5 Carcel 2000
> Nicolas 2 4 6 Carcel 2000
> Samantha 3 4 Fin Juego
> Marco 3 1 Fin Juego
> Nicolas 3 6 Fin Juego
> Ganador Matias

¿En el segundo turno de Matías, igualmente tira el dado? Si lo hago así, me dan tus mismos valores, pero si no lo tiro me dan otros. Dado que Matías cayó en la casilla 6 en el primer turno, no debería tirar dado en el segundo.

**Comment by javonunezz** [comment]
Matias como no ha terminado su juego aún puede tirar dados, eso por lo menos vi en el ejemplo del pdf

**Comment by screid** [comment]
No, Matias no puede seguir, ya que en el segundo turno avanzó hasta la casilla 6, después tiró un 2, pero como no hay más espacio para avanzar, por eso se le mesutra el mensaje de FinTurno
