### ISSUE TITLE
Error de Ejecución

### ISSUE THREAD

**Issue by NaxF11** [INS125/Laboratorio#13]
Profe he estado en repl probando mi programa, pero no entiendo cuál es mi error, no me ejecuta. La palabra que recibe de cada espacio en la linea 2, la recibe como un puntero, pero yo después trabajo con esa palabra con arreglos, y hago los cálculos y todo, y aún así no me imprime nada

**Comment by Hormash** [comment]
NaxF11, 

Intente actualizar su navegador. Al menos tome su código y me funciono en repl.it. Esta seguro que esta ejecutando el archivo correcto? o se encuentra en la carpeta correcta?
Verifique que al momento de ejecutar se encuentre en el directorio correcto.

Recuerde que la salida de los resultados debe quedar en un archivo de salida.

**Comment by NaxF11** [comment]
Sí tiene razón, me funcionó, pero me surgió otro problema. Estoy usando la entrada.txt del ejemplo 1 y de salida me imprime 6 veces los mismos números, y no siempre se ejecutan los mismos números, cada vez que lo ejecuto, varían siempre, creo que ud en una clase explico que eso era algo de imprimir el valor de los arreglos. Pero no entiendo por qué hace eso.

**Comment by Hormash** [comment]
Eso es por tu código, tienes ciertos problemas en como lees las lineas. Recuerda que ese número no siempre puede ser 6. ¿Que pasa si te pongo 1000 palabras ?
