### ISSUE TITLE
duda funcion elegirJugador()

### ISSUE THREAD

**Issue by NaxF11** [INS125/Laboratorio#130]
En el diagrama aparece que esta función debe retornar una lista, y en el enunciado dice que debo retornar el turno del jugador, y yo lo que hice fue sumarle 1 (por el orden que se nos dio la lista de jugadores) a cada jugador y luego retornar ese mismo jugador para poder trabajar con él en las siguientes funciones, pero no se si es lo que pide ud, es que no entiendo por qué retornar una lista en esa función.

**Comment by screid** [comment]
Hola! La idea es tomar una lista de jugadores y luego ir llamandola (en ese orden) para que jueguen! Esa era la idea
