### ISSUE TITLE
Consulta lectura de archivo

### ISSUE THREAD

**Issue by lvp1890** [INS125/Laboratorio#131]
Profe, tengo una duda con la lectura del archivo, quiero usar la misma funcion del laboratorio funcional 

		with open('entrada.txt','r') as f:
    	for line in f.readlines():
        	jugadores.append(line.split("\n")[0].split(" ") //pero aqui el cambio seria que en vez del yield se coloque a los jugadores[] como una lista
Esto es correcto? porque entiendo que debo separar  a los jugadores entonces como accedo a esos items mediante la lectura?

**Comment by lvp1890** [comment]
Aprovecho esta cadena para dejar mi segunda consulta: En los ejemplos vistos anteriormente, se utiliza un constructor __init__ en cada clase. De acuerdo al diagrama actualizado, esto solo debería aplicar en ciertas clases? No es necesario en todas?

**Comment by screid** [comment]
Estimado,
Debes acceder a los datos mediante el init en la clase Partida().
Con respecto a la segunda pregunta, en la versión actualizada de la tarea pusimos el constructor en las clases que se requería. Como vimos en clases el jueves, el constructor no es necesario aplicarlo a todas las clases, pero sí ayuda bastante.
