### ISSUE TITLE
¿Dónde está el archivo monopoly.py?

### ISSUE THREAD

**Issue by tomas-e** [INS125/Laboratorio#132]
Sólo me aparece el main.py.

**Comment by screid** [comment]
A cual monopoly.py se refiere? porque no se mencionó nunca ese archivo en el documento :(

**Comment by tomas-e** [comment]
Esto aparece en el repositorio creado: 
"En esta tarea usted debe editar el archivo **monopoly.py** con su correspondiente definición de clases, de acuerdo al diagrama dado en el enunciado. Si lo desea, puede modificar su función principal (main), sin embargo, la revisión se hará con una función principal como la mostrada en este archivo.

Si tiene dudas, por favor dirigirlas al foro del repositorio de nuestro laboratorio."

**Comment by screid** [comment]
Mmm quizás fue un error o malentendido, le pregunté a Matías y dijo que no se fijaran en eso, que siguieran las instrucciones del documento
