### ISSUE TITLE
Dudas con algunos atributos 

### ISSUE THREAD

**Issue by alexissaez** [INS125/Laboratorio#134]
Hola profes, tengo algunas dudas con los siguientes atributos:

Clase Jugador:
* casilla: ¿es la casilla actual en la que cayó el jugador?

Clase Carcel:
* prontuario: ¿que dato debo settear aqui? 

Clase Casilla:
* nombre: ¿lo genero con la posición de la casilla? ¿que dato debo settear aquí? 
* tipo: me imagino que es cárcel o propiedad.

Agradecería que me aclaren estas dudas.

**Comment by screid** [comment]
1) Sí, es la casilla actual del jugador.
2) Prontuario debe retornar un int, que es la cantidad de veces que caen los jugadores en la cárcel
3) Como son datos aleatorios, los nombres pueden ser genéricos (es decir, 'prontuario' y 'carcel'
4) Exacto. Es como la tres, pero es pensando que podrían tener otros nombres en el atributo nombre (por ejemplo, 'Providencia' o algo así).
