### ISSUE TITLE
¿Qué es el prontuario?

### ISSUE THREAD

**Issue by tomas-e** [INS125/Laboratorio#136]
En la clase cárcel hay un atributo "prontuario" de tipo int. ¿Qué significa?

**Comment by screid** [comment]
En el documento sale, pero es la cantidad de veces que los jugadores caen en la cárcel (es decir, es un contador básicamente)

**Comment by tomas-e** [comment]
Esto sale en el documento:

"La clase Propiedad deber´a contar
con el precio de compra, y la clase C´arcel deber´a contener un monto de fianza y un
prontuario."

Y que prontuario es un atributo de la clase Cárcel.

**Comment by screid** [comment]
Como le aclaraba en el mensaje anterior, se refiere a un contador que suma la cantidad de veces que todos los participantes han entrado a esa cárcel.
