### ISSUE TITLE
Significado números al finalizar el juego

### ISSUE THREAD

**Issue by tomas-e** [INS125/Laboratorio#137]
¿Qué significan los números al finalizar el juego?

Samantha 3 4 FinJuego
Matias 3 4 Finjuego
Marco 3 2 Finjuego
Nicolas 3 3 Finjuego

El primero parece que es el turno, ¿pero el segundo?

**Comment by javonunezz** [comment]
el numero de dados que sacaron en su ultimo turno

**Comment by tomas-e** [comment]
> el numero de dados que sacaron en su ultimo turno

Pero en el ejemplo, Samantha en el primer turno Samantha sacó 4, en el segundo sacó 2, y cuando termina aparece con un 4. ¿No debería aparecer un 2 entonces?

**Comment by javonunezz** [comment]
me refiero que Samantha en su primer turno saco un 4 en los dados, luego en su segundo turno ella saca un 2 en los dados, ella aun no termina su juego, por lo cual Samantha llega a su tercer turno y saca un 4 en los dados y eso es lo ultimo que se muestra

**Comment by tomas-e** [comment]
> me refiero que Samantha en su primer turno saco un 4 en los dados, luego en su segundo turno ella saca un 2 en los dados, ella aun no termina su juego, por lo cual Samantha llega a su tercer turno y saca un 4 en los dados y eso es lo ultimo que se muestra

Pero en el segundo turno ya termino su juego  porque llegó a la casilla 6. ¿Para qué lanzar el dado en el tercero?

**Comment by screid** [comment]
Es porque la casilla 6 sí estaba habilitada. Sin embargo, si quiero seguir avanzando (es decir, no existe la celda 7, 8 en adelante), estas celdas no existen, por lo que ahí termina mi turno.
