### ISSUE TITLE
Sólo 6 casillas. ¿Si sale mayor que siete se considera en 6?

### ISSUE THREAD

**Issue by tomas-e** [INS125/Laboratorio#138]
Si un jugador esta en la casilla 5 y en el dado sale un 6, avanza hasta el 6 y se queda ahi?

**Comment by screid** [comment]
Si tu tablero cuenta con un máx. de 6 casillas, está en la casilla 5 y el dado le dice que avance 6, como eso ya está fuera del tablero, el jugador debería terminar turno.
