### ISSUE TITLE
¿Cuáles son las condiciones de término de juego?

### ISSUE THREAD

**Issue by tomas-e** [INS125/Laboratorio#140]
¿Todos los jugadores sin dinero?
¿Todos con dinero y en la última casilla?
¿Al menos un jugador en la última casilla?

¿Qué quiere decir terminar el tablero?

**Comment by screid** [comment]
1) Los jugadores cuentan con un dinero inicial, el cual deben ingresar y es un dato de entrada, está en el .txt
2) No entiendo su pregunta, pero puede pasar que no todos lleguen a última casilla (lea el enunciado del documento, que ahí están mejor explicados las reglas).
3) No necesariamente, ídem arriba.

Se termina el tablero cuando todos los jugadores terminan su turno.

**Comment by tomas-e** [comment]
"El juego termina una vez que todos los jugadores terminaron el tablero."
Por tanto, el juego termina cuando todos los jugadores terminan su turno.

**Comment by screid** [comment]
Por que no pasa del primer turno? Si todos cuando parten aún ni siquirea recorren el tablero.
