### ISSUE TITLE
Hay algun error en el archivo de entrada? 

### ISSUE THREAD

**Issue by JuanPabloArentsenFigueroa** [INS125/Laboratorio#143]
en el archivo de entrada me tira un error al recorrerlo dice que no existe una key "Norma" para algunos ids por ej en valor 1027, 1054, etc.

**Comment by frago3** [comment]
me pasa lo mismo, el req.data arroja lo siguiente:
"b'Error al obtener la norma. Puede ser que no exista en la BD o la fecha ingresada no coincide."
¿?

**Comment by matgreco** [comment]
Hola,

Yo obtuve esos ID la semana pasada y eran válidos. Los consulté ahora y no son todos validos.

Asi que subí 2 ejemplos con el subconjunto de los IDs válidos desordenados (en el ejemplo2) y ordenados (en el ejemplo3).

La idea es que, el archivo se escriba en el mismo orden que el archivo de entrada.

En caso de que exista algún ID no válido, poner en el archivo de salida:

```
ID\tERROR
```
Por ejemplo
```
1027\tERROR
1054\tERROR
```

**Comment by matgreco** [comment]
Como dato adicional, en generar el archivo con el ejemplo3 mi programa tardó 12.4s sin ningun error en los IDs

**Comment by JuanPabloArentsenFigueroa** [comment]
Gracias profe :)
