### ISSUE TITLE
Algunos encabezados no existen)?

### ISSUE THREAD

**Issue by MrTradex** [INS125/Laboratorio#144]
Mientras me salían los resultados, me fijé que algunos encabezados me dan tipo "None". Para ser especifico, la norma 1461 según la salida que se mostró da un texto(Ejemplo del lab), pero en mi caso, me dice que no hay...
Entonces, por el momento...  dejé escrito "None" como string.
Esta bien?

**Comment by matgreco** [comment]
Lo probé y me dice `DETERMINA INTERES CORRIENTE POR EL LAPSO QUE INDICA`

**Comment by matgreco** [comment]
Corresponde a la llave Texto de la llave Encabezado

**Comment by MrTradex** [comment]
Si, Puedo PROMETER que hace un rato lo probé y me arrojaba que no tenia nada! pero lo volví a probar y me soltó eso mismo que me dijo usted ._.

**Comment by matgreco** [comment]
> Si, Puedo PROMETER que hace un rato lo probé y me arrojaba que no tenia nada! pero lo volví a probar y me soltó eso mismo que me dijo usted ._.

Si, lo que debe haber pasado es que el webservice tuvo un error y retornó diccionario vacio. Pudo deberse a un error de conexion o un error del servidor de la bcn.
