### ISSUE TITLE
problema en el tiempo de ejecución del programa

### ISSUE THREAD

**Issue by danielwarr** [INS125/Laboratorio#145]
profesor tengo 2 pc y en un computador se me demora 50 seg y en el otro se demora 90 seg , que debería hacer.

**Comment by matgreco** [comment]
yo diria que un factor determinante, mas que el pc, puede ser la conexion a internet y el tiempo de respuesta del servidor de la BCN. 

Te recomiendo probar tu programa en la madrugada con 100 threads.

El mio demoró solo 12 segundos en el ejemplo 3.
