### ISSUE TITLE
Sobre el comando de ejecución 

### ISSUE THREAD

**Issue by xiofra** [INS125/Laboratorio#146]
Profe es una duda acerca del comando de ejecución del programa , ya que , el PDF dice que es:  " python3 main.py --input=entrada.tsv --output=salida.tsv --num_workers=50" pero no me funciona ese comando en el shell de python

**Comment by Elsapallo** [comment]
si lo haces local en tu pc no lo sé jsdkldjs pero en el repl.it solo debes hacer los import y para ejecutar los comandos f1 y 'open shell'

**Comment by JuanPabloArentsenFigueroa** [comment]
tienes q ponerle --workers en vez de --num_workers

**Comment by matgreco** [comment]
con dice @JuanPabloArentsenFigueroa, el comando para ejecutarlo debe ser --workers=50
