### ISSUE TITLE
Comando para descargar librerias

### ISSUE THREAD

**Issue by lvp1890** [INS125/Laboratorio#147]
Al usar el pip install -r requirements.txt me aparece este error:
Collecting pkg-resources==0.0.0 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r requirements.txt (line 1))

que puedo hacer para solucionarlo?

**Comment by TippedJotex** [comment]
trata de instalarlo de forma manual, en este caso trata de ejecutar pip install pkg, luego pip install urllib3 y finalmente pip install xmltodict

**Comment by matgreco** [comment]
Elimina la primera linea del requirements.txt, dejalo asi 

```
urllib3==1.25.9
xmltodict==0.12.0
```

O lo otro es que los instales manualmente así

```
pip install urlib3
pip install xmltodict
```

ejecuta el programa base, si ti dice que faltan las bibliotecas es porque debes instalarlas. Tal vez ya las instalastes.
