### ISSUE TITLE
Problema con archivo de entrada

### ISSUE THREAD

**Issue by SebastianGonzalez777** [INS125/Laboratorio#148]
Hola profe, tengo un problema, lo que pasa es que con los 3 ejemplos tengo problemas, no me los muestra todos, en algun momento se cae, y me pasa con los 3 ejemplos de archivo de entrada.
Me sale este error:  
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    print(id_norma, '\t', norma[1]['Norma']['@derogado']............
KeyError: 'Norma'
256

**Comment by JuanPabloArentsenFigueroa** [comment]
tienes q usar try  y except para que se genere la salida sin q te tire ese error por q algunos ids creo q fueron modificados, el profe en una ayudantia los utiliza creo q la del martes para q veas el video q quedo guardado
