### ISSUE TITLE
duda con respecto al numero de hilos

### ISSUE THREAD

**Issue by srecamang** [INS125/Laboratorio#149]
una consulta,
que pasa si por ejemplo en el archivo de entrada hay 1000 datos y yo le asigno 30 hilos, 1000:30 = 33.33
cada hilo debería hacer 33.33 peticiones en el webservice?
saludos.

**Comment by fluushx** [comment]
Hola! no es así, mira un hilo es una petición, por lo cual 30 hilos, significa que hay 30 peticiones a la pagina de manera simultánea, entonces lo que pasa es que se ejecutan 30 peticiones al mismo tiempo, se espera que terminen todas  y luego se ejecutan nuevamente 30 más, es así sucesivamente hasta que terminen todas.
Espero poderte ayudado!
