### ISSUE TITLE
No recibo respuesta de la api hace horas

### ISSUE THREAD

**Issue by JoanMena** [INS125/Laboratorio#15]
Hace un rato estaba recibiendo respuesta de api normalmente, quiero avanzar con la tarea y no puedo ahora desde hace bastante rato, simplemente el print de la función no muestra nada y quede estancando ahora. ¿que puedo hacer? no puedo simplemente esperar a que vuelva a funcionar ya que no me queda mucho tiempo.

**Comment by JoanMena** [comment]
volví a clonar el código de nuevo para ver si había movido algo y nada aun.

**Comment by Hormash** [comment]
Como estas haciendo la consulta? Al poner la url en un navegador web tienes alguna respuesta?

**Comment by JoanMena** [comment]
no he movido nada, hace un rato funcionaba y ahora nunca mas, de hecho volvi a clonar todo el codigo. Hace un rato la respuesta se mostraba en la consola ahora solo la puedo ver ingresando la pagina en el navegador con un parametro.

**Comment by Hormash** [comment]
Si pone la url de la consulta en su navegador (agregando el numero en el size) obtiene alguna respuesta.

La api se encuentra andando sin problemas.

**Comment by JoanMena** [comment]
Pero por que antes esta funcion print(ObtenerMatriz(4)) me mostraba la respuesta por la consola del replit sin problemas y ahora no? Yo no he tocado nada del código, de echo lo volví clonar, y simplemente dejo de funcionar.

**Comment by JoanMena** [comment]
ok, ahora funciono introduciendo el comando python3 main.py --input=entrada.txt --workers=50, las primeras pruebas que hice funcionaron sin esto. No se porque ahora se llama asi si no moví nada. Listo solucionado.
