### ISSUE TITLE
Consulta sobre el buffer del primer while

### ISSUE THREAD

**Issue by DanitzaMoranC** [INS125/Laboratorio#15]
Profesor, estoy probando los textos de entrada y me ocurre que al probar la entrada del segundo texto (donde aparece la palabra revolutionary) donde mi valor de Q debe ser 7 , mi programa me muestra Q=0 con el buffer 1000, no entiendo el por qué, ya que con el texto 1 (donde aparece la palabra Content) me da el valor sin problemas (Q=6), probé aumentando el buffer a 10000 y me muestra sin problemas ambos valores de  Q. No se si lo puedo dejar así o necesariamente debe ser 1000 o que podría hacer para que mi valor de Q en el segundo texto se me asigne correctamente.

**Comment by NaxF11** [comment]
Me paso lo mismo, lo deje en 10000 para que pudiera imprimir bien los datos

**Comment by matgreco** [comment]
Hola Danitza,

Yo creo que el hash calculado para revolutionary no tiene que ver especificamente con el buffer del while, sino que tiene que ver con el tamaño (tipo) de la variable.

Debes usar unsigned long para la almacenar la suma de tu hash calculado (o de la función H(w,k)), ya que el hash para revolutionary con k=5, de acuerdo al issue #9 es:

H(revolutionary, 5) = 36323356819
por lo tanto, el hash:
hash(revolutionary, 5) = 36323356819%1000000 = 356819

Si te fijas, el valor que se debe calcular en H es mayor al rango soportado en una variable entera de 32 bits

2^32 = 4.294.967.296 (cuatro mil millones....)

Mientras que H(revolutionary, 5) = 36.323.356.819 (36mil millones)

Por lo que si usas unsigned long, que es de 64 bits, puedes almacenar numeros hasta:

2^64 = 18.446.744.073.709.551.616 (18 millones de billones..... )
