### ISSUE TITLE
Duda sobre dos funciones

### ISSUE THREAD

**Issue by lvp1890** [INS125/Laboratorio#16]
esta funcion devuelve un array en la variable numeros. Como hago para pasar esa var a la funcion hash? numeros vendria a ser mi w[0] etc... en la funcion hash
//y como hago para usar el puntero *palabra en vez de un array fijo?

**Comment by matgreco** [comment]
Borre el código por seguridad. No regale su tarea

**Comment by matgreco** [comment]
Si necesita retornar un arreglo, debe usar un puntero, definir memoria con malloc previamente

**Comment by lvp1890** [comment]
Profesor, estuve avanzando en la tarea y tengo un par de dudas que no me permiten avanzar. Son las siguientes: El puntero *palabra apunta al array linea? De ser así, debemos trabajar con ese puntero o se crea otro?

**Comment by matgreco** [comment]
No, el puntero palabra contiene la última palabra. palabra toma el array linea y lo separa por espacios, obteniendo una a una las palabras.

Usted debe tomar  "palabra" para el cálculo de su hash.
