### ISSUE TITLE
Lectura de entrada.txt

### ISSUE THREAD

**Issue by kathy-23** [INS125/Laboratorio#17]
profesor no comprendo como leer el arrego entrada.txt, agregue un archivo entrada.txt con el contenido de el ejemplo, pero nose si eso esta bien, tambien agregue una funcion para llenar un arreglo pero con numeros no con strings, como deberia hacerlo?

**Comment by matgreco** [comment]
el codigo base ya lee el archivo de entrada, usted solo debe darle el formato de acuerdo a linea. Use un contador para ver en que linea está y de acuerdo a eso ejecute alguna acción. Por ejemplo la linea 3 tiene la cantidad de palabras por las que se pregunta, entonces no es necesario separarla.

Mi recomendación es hacer una funcion que reciba un arreglo de char palabra y un entero k y dentro de la función calcúle el hash. Esa función debe retornar un unsigned long.
