### ISSUE TITLE
Incluir math.h

### ISSUE THREAD

**Issue by dzerene** [INS125/Laboratorio#18]
Hola profe, desde que se mencionó que pow daba un error de no estar definido quise ver lo que pasaba, encontré que el programa no hay que compilarlo con gcc -o exe main.c , en cambio se hace con gcc -o exe main.c -lm, entonces me entró la duda de si al momento de la revisión habría problemas por este tipo de comando, muchas gracias.

**Comment by matgreco** [comment]
Hola @dzerene,

Lo probé en mi pc con ubuntu 18.04 y tambien en repl, sin necesidad de agregar el flag -lm

```
#include <stdio.h>
#include <math.h>

int main(){
	int a = pow(2,4);
	printf("el valor de la potencia es %d", a);
	return 0;
}
```
```
>> gcc main.c -o main.o
>> ./main.o
el valor de la potencia es 16 
```

**Comment by matgreco** [comment]
no tuve ningún warning

**Comment by matgreco** [comment]
En el issue #14 di la misma respuesta.

Podrías confirmar tu SO y versión de gcc?

**Comment by dzerene** [comment]
SO windows 10, usando visual studio code con Windows Subsystem for Linux, la version de gcc es:
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by matgreco** [comment]
podrías escribir en la consola (o la windows shell), toda la salida de:

gcc -v

**Comment by dzerene** [comment]
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by matgreco** [comment]
No se en específico cual será el problema. Si te funciona con el flag `-lm` es porque en windows la biblioteca `math` se llama `m`.

Podrías interpretar que hace el flag `-lm`??

**Comment by dzerene** [comment]
Por lo que entendí, -l sirve como link a una librería, en este caso m (math)
El problema es que no sé si me servirá dejarlo así o mejor utilizo una función para realizar la potencia sin la librería para no tener errores

**Comment by matgreco** [comment]
yo creo que es por la powershell de windows. en ubuntu no es necesario agregar el flag -lm
