### ISSUE TITLE
Leer archivo de entrada + otra caso

### ISSUE THREAD

**Issue by ssozaprez** [INS125/Laboratorio#19]
Profe, ¿exactamente cómo hago para que el programa lea uno de los ejemplos que nos dieron? Sé que el código ya está hecho para leerlos, pero me refiero a cómo poner uno de los entrada.tex que nos dieron en el repo para probarlo.

Además, ¿podría darme su correo? Es para mandar otra tarea que se tiene pendiente y en las grabaciones no se ve el chat.

**Comment by matgreco** [comment]
para leerlo debes poner el archivo entrada.txt en la misma carpeta desde donde ejecutas tu programa.

Mi correo es el que está en el sistema, sacalo de ahi (para prevenir spam)

**Comment by ssozaprez** [comment]
De qué forma puedo mover el archivo? En este caso no me aparece clonar ni nada parecido para ello.

¿Por sistema se refiere a la aplicación del celular de la UNAB?

**Comment by matgreco** [comment]
Lo puedes arrastrar desde tu escritorio y soltarlo
