### ISSUE TITLE
Clone varias veces

### ISSUE THREAD

**Issue by alegrimminck** [INS125/Laboratorio#2]
Buenas profe, clone varias veces la repo, la que usaré será tarea1-alegrimminck-2

**Comment by Hormash** [comment]
Enterado. Gracias por avisar, te recomiendo mandar un mail al momento de revisar ya que se nos puede olvidar.

**Comment by alegrimminck** [comment]
Vale, en ese caso ¿Cuando será la revisión?

**Comment by matixzz9** [comment]
Profe en mi caso es lo mismo, le informo que en mi github y luego en repl.it cloné 3 veces, al pareccer quedó depositado como tarea1-matixzz9
