### ISSUE TITLE
problema guardar texto

### ISSUE THREAD

**Issue by Dmartineztoy** [INS125/Laboratorio#20]
Profe al clonar mi main.c desde github y ejecutarlo en repl guarda bien los resultados en el archivo "salida.txt" pero al ejecutarlo en mi ide del pc no me esta guardado bien y si hago printf() muestra el texto en la consola correctamente y no se como resolver ese problema.

**Comment by matgreco** [comment]
si no te arroja ningun error en tu ide, debe ser porque el archivo lo está guardando en otra ubicación. Por ejemplo en codeblocks, el programa de salida se guarda en la carpeta src o debug. Verifica eso. 
Si no, podrías darnos mas datos del problema como el ide, el sistema operativo, etc.

**Comment by Dmartineztoy** [comment]
se guarga donde debe ya que crea el archivo "salida.txt" en la carpeta solo que no esta sirviendo la funcion fprintf(salida,"....") no "escribe" dentro del archico

**Comment by matgreco** [comment]
con tan pocos datos no podría adivinar que es. Esto tiene mas que ver con tu entorno de programación que con la tarea.

Pruebalo no con un ide. Ejecutalo por consola
