### ISSUE TITLE
Consulta lineas ejemplo 2

### ISSUE THREAD

**Issue by javonunezz** [INS125/Laboratorio#21]
Profe en el ejemplo 2, el texto utiliza mas de una linea en el archivo txt por lo cual el Q no se encuentra en la tercera linea, entonces ¿ se revisará el programa utilizando archivos  txt donde el Q se encuentre en la tercera linea?.

**Comment by matgreco** [comment]
Es la tercera linea. Es el ajuste de linea lo que hace que se vea asi.

Puedes vero en el github, donde están las lineas enumeradas:

https://github.com/INS125/Laboratorio/blob/master/Tarea1/ejemplo1/entrada.txt
https://github.com/INS125/Laboratorio/blob/master/Tarea1/ejemplo2/entrada.txt

**Comment by javonunezz** [comment]
Ok, gracias profe.
