### ISSUE TITLE
No puedo guardar "k"

### ISSUE THREAD

**Issue by Ronkoi** [INS125/Laboratorio#22]
Profe, intento guardar la variable "k" pero por lo que he intentado, la manera en que se lee el archivo es con un puntero char y si lo trato de guardar me dice que no son compatibles, intenté unos códigos que cambiaban un char a int, pero aún así tampoco pude por lo mismo.

**Comment by Hormash** [comment]
Recuerde que la variable 'k' se encuentra en la primera linea. Tomando esto en cuenta debe convertir el valor que representa el carácter a entero, no su valor en ASCII.

Esto dado que el valor de 'k' viene como un caracter ej '5'.
Debe castear el valor antes de guardarlo.

https://github.com/INS125/Laboratorio/tree/master/03
