### ISSUE TITLE
problemas al compilar

### ISSUE THREAD

**Issue by JavierToro** [INS125/Laboratorio#24]
Estuve leyendo los otros inssues de otros alumnos que tienen el mismo problema que yo. Y es cuando compilo en el repl con el comando gcc main.c -o main.o, me dice que no esta definido pow para poder elevar un numero en el hash, ya tengo la biblioteca math.h
Este es mi salida en el terminal:
 gcc main.c -o main.o
/tmp/ccnc4AwS.o: In function `hash':
main.c:(.text+0x7a): undefined reference to `pow'
collect2: error: ld returned 1 exit status


**Comment by matgreco** [comment]
Incluiste math.h?

Yo demostré que en repl y ubuntu nativo no es necesario ningún Flag de
compilación

**Comment by JavierToro** [comment]
Si lo incluí, igualmente programe al final una función para elevar un numero, pero me sigue sin funcionar el pow en el repl

**Comment by JeanContreras12** [comment]
yo tuve el mismo problema y vi la solucion aqui https://www.linuxito.com/programacion/765-gcc-undefined-reference-to-pow , que dice que aveces hay que linkear la libreria directamente agregando un -lm al final del compilador ./gcc main.c -o main.o -lm , almenos asi me compilo a mi

**Comment by matgreco** [comment]
hola @JavierToro.

Math.h está en mi biblioteca y funcionará sin -lm, no hay problema con eso.

Muy buena tu investigación @JeanContreras12 , muchas gracias por compartir el link con nosotros. Aún no encuentro una explicación a por que, con la misma versión de gcc y SO en repl.it, a mi nunca me ha pedido decirle al linker que tome la libm.o.

en el caso de ustedes, estaban usando repl, linux nativo o powershell en windows?

**Comment by matgreco** [comment]
Ya, creo que descubrí algo.

Lo cual probablemente tenga que ver con la etapa de optimización o preprocesado del código.

Cuando uno llama a la función pow de la siguiente forma.

```
int tt = pow(1,2);
```
El programa compila perfectamente, sin el flag -lm. Es probable que esto tenga que ver con la etapa de preprocesamiento que reemplaza el valor por un número, para no ejecutar el cálculo durante la ejecución.

Mientras que este ejemplo si da error.
```
int x = 1;
int tt = pow(x,2);
```
Y ahí si se requiera dicho flag.

Pero no hay problema, usenlo nomas. agregaremos -lm al comando de compilación.
