### ISSUE TITLE
error compilación

### ISSUE THREAD

**Issue by Erick-Peralta** [INS125/Laboratorio#26]
Hola, al momento de compiar el archivo base me manda este error:

clang version 7.0.0-3~ubuntu0.18.04.1 (tags/RELEASE_700/final)
 clang-7 -pthread -lm -o main main.c tarea1-Erick-Peralta/main.c
/tmp/main-ce05a4.o: In function `main':
main.c:(.text+0x0): multiple definition of `main'
/tmp/main-ef555b.o:main.c:(.text+0x0): first defined here
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
compiler exit status 1

A que se puede deber? solo compilé el archibo main.c base (sin alteraciones de mi parte) y me arrojó ese error :(

**Comment by Erick-Peralta** [comment]
Hay dos main.c, uno que viene por defecto fuera de la carpeta, y otro main.c que se encuentra dentro de la carpeta de la Tarea, en el codigo del main.c que esta fuera de la carpeta le puse 
#include <stdio.h>

int main2(void) {
  printf("Hello World\n");
  return 0;
}

Al main le puse un 2 y ya no me sale el error anterior, me sale uno nuevo que dice falla de segmentacion exited, segmentation fault

**Comment by matixzz9** [comment]
Hola, presento el mismo error y en caso de pober int main2(void) 
me corre el main.c del inicio y no el de la tarea.
clang version 7.0.0-3~ubuntu0.18.04.1 (tags/RELEASE_700/final)
 clang-7 -pthread -lm -o main main.c tarea1-matixzz9/main.c
/tmp/main-29a0ad.o: In function `main':
main.c:(.text+0x0): multiple definition of `main'
/tmp/main-02c312.o:main.c:(.text+0x0): first defined here
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
compiler exit status 1

**Comment by matgreco** [comment]
y si en vez de ponerle main2, borra el contendio del archivo main.c que no le sirve?

**Comment by matgreco** [comment]
compilando por consola no da error, lo acabo de comprobar. Es porque intentas compilar y ejecutar con el boton run.

https://i.imgur.com/ZUXROyT.png

**Comment by Erick-Peralta** [comment]
Hola profe, ya solucione el problema, el tema es que al usar el boton Run para compilar (me aparece un warning reference a la funcion gets();) puedo hacer correr el programa normalmente, pero ahora usando la compilacion por consola no me deja seguir por ese warning

**Comment by matgreco** [comment]
los warning si dejan seguir. Es probable que todo este bien y haya generado el archivo.

gets viene de stdio.h, verifica que esté el macro que la incluye
