### ISSUE TITLE
Error al compilar

### ISSUE THREAD

**Issue by JeanContreras12** [INS125/Laboratorio#27]
al compilar me tira el error Segmentation fault (core dumped), hice unos printf y unos scanf en el main antes del código que nos entregaron ustedes y tambien cree una funcion, compila todo bien pero al momento de ejecutarlo pasa por el printf y el scanf pero luego me lanza el error de segmentación.

Tambien tengo una duda si el .txt tiene que estar dentro de mi rpl para poder abrirla?

**Comment by matgreco** [comment]
eso puede ser porque desde la ejecución no está logrando abrir el archivo o porque sobrepasa el tamaño de algún arreglo.

el txt debe estar en la carpeta de su programa.o generado por la compilación. verifique eso al hacer la compilación.

si compila con gcc tarea1-usuario/main.c -o main.o, su programa de salida estará afuera de la carpeta.

**Comment by JeanContreras12** [comment]
listo me faltaba meterlo dentro de la carpeta gracias profe
