### ISSUE TITLE
gcc en windows 

### ISSUE THREAD

**Issue by frago3** [INS125/Laboratorio#3]
hola profe,
Me di cuenta de que en las instrucciones indica que para hacer el trabajo hay que usar linux o relpit.
puede variar el programa si lo compilo en gcc de windows?

**Comment by matgreco** [comment]
Si, podría variar un programa hecho en windows que en linux, ya que algunas
bibliotecas tienen implementaciones distintas.

Sin embargo, le puedo recomendar hacer su tarea en windows y una vez que la
termine verifique que funciona en linux.

Ojo también que en windows los saltos de línea son \r\f y en linux son \n.
Eso hará que deba copiar su código fuente en un editor nuevamente. Podemos
verlo en el lab en caso que tenga problemas.

**Comment by matgreco** [comment]
Para eso no necesitas un lambda por obligación, aunque igual se puede hacer. 

Piensa que la diagonal de la matriz con las columnas invertidas es simplemente multiplicar por la misma "lista" pero invertida, y considerar el lista[0] * lista_invertida[0] + lista[1] * lista_invertida[1] +  ..... + lista[n] * lista_invertida[n]

donde n es el largo de la secuencia.
