### ISSUE TITLE
aclaración de carpeta, clone #3 veces

### ISSUE THREAD

**Issue by fluushx** [INS125/Laboratorio#30]
Profesor, creo que cloné varias veces el repositorio, subi el archivo acá! 
INS125/laboratorio0-fluushx

**Comment by fluushx** [comment]
me avisa si lográ encontrarlo sino para subirlos nuevamente

**Comment by matgreco** [comment]
Hola @fluushx 

No importa cuantas veces clones tu repositorio. Solo fíjate que en la ruta que indicas esté el trabajo que quieres entregar.

Yo por ejemplo, tengo 2 computadores. Clono mi repositorio en los dos computadores. Trabajo en el computador A y le hago commit push. Luego llego al computador B y le hago pull (bajar los cambios desde el repositorio remoto al repositorio local) con eso tengo los cambios actualizados, y trabajo sobre eso para luego hacerle commit push... etc.
