### ISSUE TITLE
Salida.txt ejemplo 1

### ISSUE THREAD

**Issue by nicolasbalbontin** [INS125/Laboratorio#32]
Profesores:
 Tengo una duda que en el archivo de salida hago que me salgan los valores, pero el ultimo valor me sale primero:
El Valor Hash es :4433
El Valor Hash es :453
El Valor Hash es :97
El Valor Hash es :123997
El Valor Hash es :124029
El Valor Hash es :4028
me tira así. 
nose si me lo considerarían bueno o no .
Quedo atento a comentarios.

**Comment by matgreco** [comment]
no, eso está incorrecto
