### ISSUE TITLE
Salita.txt

### ISSUE THREAD

**Issue by blpezsandoval** [INS125/Laboratorio#34]
Profesor.
Tengo un problema con el salida, ya que hice que el programa creara el salida.txt y no crea un archivo, pero al usar el comando ls en el repl me muestar el salida.txt. ¿esta bien eso?

**Comment by abraham2323** [comment]
pude ser que se no este refrescando prueba a volver a cargar la pagina y ve si te aparece

**Comment by blpezsandoval** [comment]
vale wachin, re capo
