### ISSUE TITLE
¿Profe, es normal que me aparezca un error en el archivo matriz.c sin hacerle cambios?

### ISSUE THREAD

**Issue by valeuwu** [INS125/Laboratorio#39]
Me aparece: 
c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../libmingw32.a(main.o):(.text.startup+0xa0): undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status

no le hice ningún cambio de momento, pero no entiendo a que se refiere este error

**Comment by matgreco** [comment]
debe ser porque quiso ejecutar su programa sin los parámetros de entrada.
