### ISSUE TITLE
Ejemplo de archivo de salida.txt

### ISSUE THREAD

**Issue by frago3** [INS125/Laboratorio#4]
Profe, no se si entedí bien como definir la funcion hash.
En le ejemplo de archivo de salida que aparece en el pdf del trabajo,  indica lo siguiente:

"En el ejemplo hash(or,3) = 453, hash(a,3) = 97, etc
453 1
97 3"

En el caso de hash(or, 3) la función, según entindo, debería sumar "o * k" y "r * k", entendiendo que k = 3; osea 

(o * k)     + (r  *  k)
(111 * 3) + (114 * 3) = 675

Lo revisé así, y no me cuadran los resultados del archivo de salida.
Ayuda , pls.

**Comment by matgreco** [comment]
Esta correcto excepto que es k elevado a 0 y k elevado a 1.

111*3^0 + 114*3^1
