### ISSUE TITLE
Duda sobre for

### ISSUE THREAD

**Issue by Nato18** [INS125/Laboratorio#4]
se puede utilizar for dentro de las funciones que usted entrego? y si o si se deben utilizar las funciones reduce, map y filter dentro de esas funciones? es que por ejemplo yo tengo una variable map(conversionNumerica,Secuencia) y dentro de conversionNumerica no uso esas funciones solamente remplazo las letras. por eso me surgieron la duda.

**Comment by matgreco** [comment]
Si, se puede (aunque me gustaría mas que no lo usara).

Solo considera que esas funciones reciben 1 secuencia, por lo que despues en el "main" del programa debes recorrer el iterable que contiene cada examen con un map o un filter para aplicarlo a todos los examenes.
