### ISSUE TITLE
Profe, estoy con el codigo en repl y me tira un error

### ISSUE THREAD

**Issue by valeuwu** [INS125/Laboratorio#41]
Cree un repositorio nuevo(para no mezclarlo con el del trabajo) y no me toma ningún archivo, incluso el main.
El error que sale es: segmentation fault (core dumped)

**Comment by Hormash** [comment]
Podrías agregar más información a tu respuesta pls =]
- ¿Como estas compilando?
- ¿Como estas ejecutando?
- ¿Donde se encuentran los archivos?

**Comment by valeuwu** [comment]
Cuando presiono RUN aparece esto: error: linker command failed with exit code 1 (use -v to see invocation)
compiler exit status 1 

Estoy utilizando:
 gcc main.c matriz.c -o main  
./main -a mUno.in -b mDos.in -l 4 -f filG.in -s suma.out -c conv.out 

cree una carpeta en donde tengo el main.c matriz. matri.h y los archivos de entrada

me moví a la carpeta para la compilación y ejecución

**Comment by Hormash** [comment]
Si, con el botón RUN dará un error al ejecutar su programa. Tener en cuenta que al momento de ejecutar debe estar en la misma carpeta y los archivos de entrada también.

Recuerde que el comando `ls`  lista todo los archivos dentro de la carpeta.
Y `pwd` indica en la carpeta donde se encuentra.

También que los archivos de entrada deben tener el mismo nombre que se dan por parámetros.

Si el problema persiste háganos saber.

**Comment by isidoragomez** [comment]
Quería consultar porque tengo un error parecido, pero con el segmentation fault (core dumped)
Sé que tengo tiene que ver con la memoria, ¿pero dónde?
Estoy solo con el código base sin haberle hecho ningún cambio.

**Comment by matgreco** [comment]
@valeuwu e @isidoragomez 

Verifiquen

1. Que en la carpeta que está su archivo main.c tambien estén los archivos con extension in (mUno.in, mDos.in y filG.in).
2. Luego verique que al hacer ls se listen los archivos antes mencionados, los dos archivos .c (main.c y matriz.c) y el archivo .h. Esto para verificar que están en la carpeta correspondiente y no en la raiz.
3. Luego compile con el comando dado y ejecute ingresando los parámetros de entrada.

Ḿi conjetura, sin tener mucha información al respecto, es que su programa no está tomando los archivos de entrada.

**Comment by valeuwu** [comment]
ya me corre el programa, gracias profe :)

**Comment by matgreco** [comment]
pero cual era el problema?

**Comment by valeuwu** [comment]
darle bien el tamaño de la matriz cuando la leyera del archivo :' )

**Comment by isidoragomez** [comment]
Cambié el 4 por el 3, verifiqué que estuvieran todos los archivos y me sigue dando segmentation faul

**Comment by Hormash** [comment]
@isidoragomez Trate de verlo en el laboratorio. Puede ser mañana en el laboratorio o en el que hago yo el sábado. 
Me dice.

**Comment by isidoragomez** [comment]
¡Gracias, profe! Ya lo solucioné, gracias :'D

**Comment by matgreco** [comment]
Y que era? Le agradeceríamos que pusiera la solucion al problema

**Comment by matgreco** [comment]
@isidoragomez

**Comment by isidoragomez** [comment]
Al pasar los archivos de ejemplo con un salto de linea en el nombre del archivo, no los reconoce.
