### ISSUE TITLE
free( ) liberar memoria

### ISSUE THREAD

**Issue by frago3** [INS125/Laboratorio#42]
Hola, profe

Cuando corro el programa en windows a veces se queda pegado justo antes de terminar. 
Generalmente corre dos veces bien y a la tercera se cae.
Intuyo que puede ser un problema de memoria, porque se pega justo al final despues de hacer las operaciones, en la parte donde estan los free( ).

Al pricipio solo tenia free( matrizA), free (matrizB), etc.
despues de averiguar lei que hay que liberar tambien lo que se reserva por filas:

 for(int i = 0; i < tamano; i++)
    free(ptr[i]);
free(ptr); 

pero sigue ocurriendo lo mismo.
¿?

**Comment by Hormash** [comment]
Pruebe si lo hace para cada posición de la matriz. Y en linux le pasa lo mismo?

**Comment by frago3** [comment]
Si, creo que estaba declarando mal tamaño de una matriz lo que, al parecer, generaba conflicto al momento de recorrer las filas para liberar la memoria. Ya no me pasa.
Gracias profe.
