### ISSUE TITLE
consulta de salida

### ISSUE THREAD

**Issue by katherin5928** [INS125/Laboratorio#43]
profe una consulta la salida del trabajo que diferencia tiene con la salida del trabajo 1 es que como definieron getopt me confundí. 

tan solo tengo que generar un archivo txt pero el getopt que pasa con eso?? hace algo diferente para generar mi archivo txt, aparte de trabajar con punteros?

**Comment by Ronkoi** [comment]
De hecho creeeo, que hay que generarlos con la extensión .out si seguimos las indicaciones de los ejemplos y el getopt. No creo que afecte en el cómo ingresar los datos de todas maneras.

**Comment by katherin5928** [comment]
ahhh.... ya ahora entiendo gracias.

 @Ronkoi
