### ISSUE TITLE
error al agregar mis funciones 

### ISSUE THREAD

**Issue by katherin5928** [INS125/Laboratorio#44]
Profe no entiendo porque me tira error mi programa, pues agregue mis funciones y me sale:

Segmentation fault (core dumped)

Luego deje de llamar mis funciones del main y me sigue saliendo lo mismo no se porque.

**Comment by matgreco** [comment]
@katherin5928, la verdad para nosotros es muy dificil (mas bien diria imposible) adivinar por que su programa tira segmentation fault.

Pruebe ocupando el depurador GDB el cual le dará pistas sobre donde puede encontrarse el problema. Aquí encuentra las instrucciones https://github.com/INS125/Laboratorio/tree/master/06

**Comment by katherin5928** [comment]
Profe me surgieron 3 preguntas,las cuales son:


1)El filtro siempre va a ser una matriz de 3x3?
2)Siempre la matriz A y B  van a ser de igual tamaño?
3)Siempre la matriz A y B va a ser más grande o de igual tamaño que el filtro.O puede ser más pequeña la matriz A y B a comparación del filtro? 
  
@matgreco

**Comment by katherin5928** [comment]
Tengo otra duda sobre mi programa es que hice mi programa y me funciona en Repl pero  me crea tan solo un archivo  correspondiente el de suma y el de convención de las matrices no, y no entiendo el porque.

Por otro lado intente de hacerlo nuevamente en otro Repl copiando el código tal cual para ver si era error de Repl pero me sale  error de nucleo. Sin embargo en el otro no me pasa eso solo me pasa lo que dije anteriormente, me crea solo el txt el de la suma. Mi duda es como saber si ocurrirá ese error cuando lo ejecuten ustedes o como saber cual de los dos Repl me dice el verdadero error.

**Comment by katherin5928** [comment]
ya lo solucione pero porque no me crea el archivo de convención pero si el de suma. :/

**Comment by katherin5928** [comment]
ya lo solucione :D
