### ISSUE TITLE
Duda para compilación

### ISSUE THREAD

**Issue by Erick-Peralta** [INS125/Laboratorio#46]
Profesor una pregunta, 

1) Para compilar debo juntar todos los códigos? me refiero a colocar los codigos de los archivos matriz.h y matriz.c  dentro del main.c? o solo basta con compilar el archivo main.c? (Y de que forma debo compilar? (pregunta 2))

2) Para compilar sé que tengo que estar dentro de la carpeta. Para ello me aseguro de poner el comando ls y me arroja esto:

 ls
main  main.c  matriz.c  matriz.h  README.md

Eso me informa que ya me encuentro dentro de la carpeta con los respectivos archivos.

Una vez realizado ese paso de qué forma procedo a compilar? y cual archivo? (relacionado a la pregunta 1), ya que por ejemplo le doy al botón RUN del archivo main.c y me arroja el siguiente error:

 clang-7 -pthread -lm -o main main.c tarea2-Erick-Peralta/main.c tarea2-Erick-Peralta/matriz.c
tarea2-Erick-Peralta/matriz.c:5:1: warning: control reaches end of non-void
      function [-Wreturn-type]
}
^
tarea2-Erick-Peralta/matriz.c:10:1: warning: control reaches end of non-void
      function [-Wreturn-type]
}
^
tarea2-Erick-Peralta/matriz.c:31:33: warning: inequality comparison result
      unused [-Wunused-comparison]
        fgets (linea, 5000, fp) != NULL;
        ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
3 warnings generated.
/tmp/main-cd52ce.o: In function `main':
main.c:(.text+0x0): multiple definition of `main'
/tmp/main-6379fb.o:main.c:(.text+0x0): first defined here
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
compiler exit status 1



Y lo mismo me pasa si compilo con el boton RUN los otros archivos (matriz.h y matriz.c)

En cambio si coloco el codigo de compilación en la consola (gcc main.c matriz.c -o main) para cualquier archivo no me arroja nada, se queda sin nada y me salta a una linea vacía

 gcc main.c matriz.c -o main
 

Muchas gracias

**Comment by Erick-Peralta** [comment]
Actualización:

Ahora probé colocando el codigo de ejecución en la consola y efectivamente me compila son problemas: (estando dentro de la carpeta ls con los archivos correspondientes)

 ./main -a mUno.in -b mDos.in -l 4 -f filG.in -s suma.out -c conv.out
Hello World asd
Segmentation fault (core dumped)
 

Ese Hello world asd lo puse para ver si me compilaba correctamente y asegurarme de que me saliera algo ya que aun no introduzco el código para suma

Sin embargo, aun me queda la duda 1) respecto a si debo juntar todo el codigo de los archivos en 1 solo y tambien la pregunta 2) ya que lo que acabo de hacer con el codigo de ejecución que puse recientemente no sé si es la manera correcta.

Saludos y muchas gracias

**Comment by Hormash** [comment]
El comando para compilar es 
` gcc main.c matriz.c -o main`
La linea vacia que se muestra quiere decir que no hubo problemas de compilación. El boton RUN no sirve para este código.

Como su código compilo luego lo ejecuto con el comando
` ./main -a mUno.in -b mDos.in -l 4 -f filG.in -s suma.out -c conv.out`

Y su programa se detuvo con un 
`Segmentation fault (core dumped)`

- ¿Existen los archivos de entrada?
- Las matrices son del tamaño indicado (en este caso 4)
- ¿El formato de los archivos esta correcto?
