### ISSUE TITLE
Error con el depurador GDB

### ISSUE THREAD

**Issue by JeanContreras12** [INS125/Laboratorio#47]
hola profe, tengo una duda con el depurador, simplemente replique mi repl y lo ejecute y me genera segmentation faul, asi que fui a usar el depurador con los pasos indicados aca https://github.com/INS125/Laboratorio/tree/master/06  al momento de darle run me dice 
Starting program:  
warning: Error disabling address space randomization: Operation not permitted
No executable file specified.
Use the "file" or "exec-file" command.
(gdb)
no entiendo bien cual es el problema

**Comment by JeanContreras12** [comment]
cuando ejecuto el gdb main.o
 me dice main.o: No such file or directory.
estoy compilando con: gcc main.c matriz.c -o main --debug

**Comment by JeanContreras12** [comment]
creo que el problema puede estar en la linea
fgets (linea, 5000, fp) != NULL;

no se que deberia cambiarle por que viene del codigo base aparece en verde la correccion y dice 
inequality comparation result unused

**Comment by matgreco** [comment]
al compilar tu archivo se llama **main** y al  correr gdb pides **main.o**

**Comment by JeanContreras12** [comment]
Program received signal SIGSEGV, Segmentation fault.
_IO_fgets (buf=0x55b3e5876060 <linea> "", n=5000, 
    fp=0x0) at iofgets.c:47
47  iofgets.c: No such file or directory.

eso me dio el depurador, que deberia aplicarle?

**Comment by matgreco** [comment]
no le estas pasando los parametros de entrada

ahi dice que fgets necesita un archivo y no está el archivo. Es porque o no le estás pasando el nombre del archivo o no tienes el archivo en la ruta que le entregas

**Comment by JeanContreras12** [comment]
añadi a mi tarea2 los mismos archivos del ejemplo 1 y con los mismos nombres, los mismos que ingreso con el ./main -a mUno.in -b mDos.in -l 4 -f filG.in -s suma.out -c conv.out
pero me sigue dando el segmentation fault

**Comment by Hormash** [comment]
En el ejemplo 1 las matrices de entrada son de tamaño 3, por lo que el -l 4 provoca un segmentation fault
