### ISSUE TITLE
Duda con la convolucion

### ISSUE THREAD

**Issue by lvp1890** [INS125/Laboratorio#48]
Respecto a la convolución, cuando tomo los 4 pivotes que eran 6, 7,10,11 del ejemplo  debo hacer matrices de 3x3. Debo enfocarme en los bordes? Como recorrer columna-1 o fila-1? Se aplica lo mismo en cada caso, como cuando el pivote es 10? Pero esto no aplicaria a una matriz mas grande como 7x7 o de tamaño mayor a 4x4.

**Comment by Hormash** [comment]
Los valores de los bordes no se toman como pivotes. Pero para realizar el calculo de la convolución debo seleccionar los ocho números que lo rodean, incluyendo si el valor esta en el borde o no.

(no se si respondí tu pregunta)

**Comment by lvp1890** [comment]
Hola, mi duda es si debo enfocarme en los pivotes o simplemente partir de lado izquierdo de la matriz e ir avanzando como un deslizador que va aumentando , porque si me fijo en los pivotes para una matriz mas grande, el calculo no seria el mismo.

**Comment by Hormash** [comment]
¿Que quieres decir con pivotes?

Se le debe realizar la convolución a los elementos que no están en el borde de la matriz. Pero para realizar el calculo de la convolución se debe considerar a la matriz completa.

**Comment by lvp1890** [comment]
gracias profe, lo hice tomando en cuenta la matriza completa para el calculo y funciono.
