### ISSUE TITLE
Duda funciones con el parámetro tamaño

### ISSUE THREAD

**Issue by Erick-Peralta** [INS125/Laboratorio#49]
Profe una consulta, sucede que ya tengo lista mi funcion de suma de matrices, usando el parámetro tamaño para recorrer el ciclo for y lo mismo para la función escritura de matrices que el parámetro lo uso para los ciclos for. Pero me salta una duda, a la hora de posicionarme en el main por ejemplo uso las variables que ya están definidas (**Matriz A **Matriz B) y las pongo en los parámetros de la función: suma (Matriz A, MatrizB, tamaño) pero justamente me queda ese parámetro llamado tamaño que no sé cómo usarlo en el main, lo único que se me ocurrió fue declarar una variable de tipo int tamaño en el main y nada más pero no sé me ocurre una manera correcta de uso, alguna pista?

**Comment by matgreco** [comment]
el tamaño de la matriz tambien es un parámetro de entrada del programa

-l
