### ISSUE TITLE
consulta 

### ISSUE THREAD

**Issue by katherin5928** [INS125/Laboratorio#50]
Profe sabe que el repl me esta tirando error en la funcion convolucion cuando declaro:

 int tam=tamano-2;

porque se provoca eso ?
Es que me di cuenta porque comencé a borrar linea por linea hasta que me tirara error para lanzar el txt de convolucion y cuando agregue eso me tira error.

**Comment by katherin5928** [comment]
la verdad e mirado mi codigo y aun no entiendo el error en la función de convolucion ya que si borro todo lo que esta dentro de la función me ejecuta super bien mi programa

**Comment by Hormash** [comment]
¿Podría indicar el error de la compilación o cuando se ejecuta?, por favor

**Comment by katherin5928** [comment]
me dice Segmentation fault (core dumped) pero si borro todo no me tira ese error

**Comment by katherin5928** [comment]
la verdad e intentado de todas formas para ver el error de mi código pero sigo sin comprender cual es el error si segun yo asigno bien la memoria incluso intente de poner un static pero aun asi me tira error

**Comment by Hormash** [comment]
mmm, en su código da Segmentation fault dado que esta accediendo a una posición que no se puede.
Fijese en su segundo for para la convoluvión

**Comment by katherin5928** [comment]
Bueno ahora vi que tenia un i en ves de un j pero aun asi me creo el archivo de salida de convolucion pero esta ves sin nada y me sigue tirando el mismo error.

antes no me tiraba ese archivo a si que igual fue un avance jaja pero consulta, me dice que revise el for de la creación de mi nueva matriz o de mi asignación a la nueva matriz

**Comment by Hormash** [comment]
Es por la escritura de la matriz, por eso se cae. Verifique el formato de salida

**Comment by katherin5928** [comment]
pero porque cuando pongo por  ejemplo un return de matriz en la función de convolucion no me tira ese error .Pero si me lo tira cuando hago el return de mi matriz creada. Es significa que mi creación de la matriz y la asignación en la posición de la matriz creada están  bien o no?

**Comment by Hormash** [comment]
- ¿De que tamaño en la matriz de la convolución?
- ¿Cuando manda a escribir la matriz que tamaño enviá? (segunda llamada)

**Comment by katherin5928** [comment]
ya entendí muchas pero muchas gracias Profe :)))
