### ISSUE TITLE
Falta de archivo iofgets.c

### ISSUE THREAD

**Issue by Erick-Peralta** [INS125/Laboratorio#51]
Profe una consulta, aún me sigue saliendo el error de Core Dumped y ya tengo los dos archivos de entrada dentro de la carpeta de trabajo, de hecho aun no realizo la función de la convolución ni tampoco de la escritura de archivos por lo que el comando que estoy ejecutando es el siguiente: 
./main -a a.in -b b.in -l 3

En el archivo a.in esta la matriz A que es de tamaño 3x3, lo mismo para el archivo b.in, sin embargo aún asi acortando el comando de ejecución me sigue mandando el error, por otro lado, para probar, agregué los archivos restantes (sin nada de contenido) para probar el comando completo:

./main -a mUno.in -b mDos.in -l 3 -f filG.in -s suma.out -c conv.out

y me vuelve a salir el mismo error, por lo que usé el depurador para ver si me detallaba el error y esto fue lo que me salio:

(gdb) run
Starting program: /home/runner/Tarea2/tarea2-Erick-Peralta/main.o 
warning: Error disabling address space randomization: Operation not permitted

Program received signal SIGSEGV, Segmentation fault.
_IO_fgets (buf=0x55abb536f060 <linea> "", n=5000, fp=0x0) at iofgets.c:47
47  iofgets.c: No such file or directory.

Que puede ser? muchas gracias

**Comment by Hormash** [comment]
¿Existe el archivo filG.in con la matriz filtro?

Una duda, ¿acepto la tarea y/o actualizo su repositorio?

**Comment by Erick-Peralta** [comment]
Profe ya lo pude solucionar, cloné nuevamente el repositorio, añadí todos los archivos (mUno.in mDos.in filG.in suma.out conv.out, etc) y ahora me funciona correctamente, muchas gracias
