### ISSUE TITLE
duda sobre los archivos.in

### ISSUE THREAD

**Issue by danielwarr** [INS125/Laboratorio#52]
En mi carpeta de tarea dos cree todos los archivos de Ma.in y Mb.in y filG.in , pero no logro hacer que me corra el programa y que menos me lea los archivos que introduzco.

**Comment by Hormash** [comment]
Si nos cuenta que realiza para correr los archivos tal vez podríamos ayudar. ¿Que utilizar para compilar y ejecutar?

**Comment by danielwarr** [comment]
uso dev c++

**Comment by Hormash** [comment]
Bueno, por tu respuesta voy asumir que apretar el botón run, que compila y ejecuta. Si realizas eso no va a funcionar.
Para compilar debes utilizar el comando que aparece en el enunciado del trabajo (creo que incluso esta comentado en el código base), eso lo puede modificar en dev c++ para que cada vez que compiles lo haga con el comando entregado.

Para la ejecución pasa exactamente lo mismo, hay una serie de parámetros que se entregan en la ejecución si realizas un
`./main`
El programa no va a ejecutar bien.

**Comment by danielwarr** [comment]
y donde pongo ese comando en el dev c++

**Comment by Hormash** [comment]
Nose, yo no ocupo dev c++. Puede realizar todos los comando por consola
