### ISSUE TITLE
Duda sobre Segmentation fault

### ISSUE THREAD

**Issue by MrTradex** [INS125/Laboratorio#53]
Buenas profe, resulta que si tan solo me saliera el Segmentation fault sabia que es un problema para acceder a "algo" pero resulta que el error entero me sale asi: 

Segmentation fault (core dumped)

Que significa esto?

**Comment by Hormash** [comment]
Que salio fuera del tamaño permitido del arreglo. 

int arr[10];
arr[10] --> Segmentation fault (core dumped)
