### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by nsalinash** [INS125/Laboratorio#54]
Es normal que el código base sin hacerle ningún cambio, compilando y ejecutado segun sale en los comentarios del main.c , y con los archivos que salen en el ejemplo tire el error Segmentation fault (core dumped) ??

**Comment by Hormash** [comment]
- ¿Existen los archivos de entrada?
- Las matrices son del tamaño indicado (el número después de -l)
- ¿El formato de los archivos esta correcto?

**Comment by nsalinash** [comment]
Era el tamaño de la matriz, pensé iba a estar correcto al venir en el código como ejemplo.
Gracias.
