### ISSUE TITLE
Duda en una funcion

### ISSUE THREAD

**Issue by Joaquin-Cortes** [INS125/Laboratorio#55]
Hola profe,  tengo una duda, si es que en la funcion int ** convolucion(int **matriz, int **filtro, int tamano) le puedo agregar  mas parametros?
saludos

**Comment by Hormash** [comment]
Si puede, mientras el formato de los parámetros de entrada o salida todo bien.

**Comment by Joaquin-Cortes** [comment]
gracias profe
