### ISSUE TITLE
Consultas varias

### ISSUE THREAD

**Issue by Erick-Peralta** [INS125/Laboratorio#56]
Profe, dado que tengo lista mi funcion suma del archivo matriz.c voy en la parte
del main del archivo matriz.c y me surgen dos preguntas

1) al final del main se define por ejemplo int **matrizA = lecturaMatri(...)

Lo que hace aquello es guardar en ese puntero doble la matriz que viene dentro del fichero que contiene mi matriz uno?

2) De lo anterior declaré los parámetros de sumamatrices con esas Variables matriz A, matriz B y largo que se encuentran al final del main pero tampoco sé si será lo correcto

3) en la función escritura Matriz del archivo matriz.c tengo casi todo listo, declaré el fichero y a fopen le pasé el parámetro filename quedándome fopen(filename...) y posteriormente puse 2 ciclos for desde i hasta el parámetro size que viene por defecto en la función pero dentro de estos ciclos no sé cuál función usar para que me escriba dentro del archivo si fscanf o fwrite o cual?

Muchas gracias

**Comment by Hormash** [comment]
1. al final del main se define por ejemplo int **matrizA = lecturaMatri(...) 
 - Si, se puede decir que es la primera matriz.
2. De lo anterior declaré los parámetros de sumamatrices con esas Variables matriz A, matriz B y largo que se encuentran al final del main pero tampoco sé si será lo correcto
- No te entiendo bien, pero en otras palabras estás haciendo la suma de matrices, por lo que estaría correcto.
3. [...]
- Tiene libertad para ello, se le solicita que el archivo de salida tenga el formato correcto que se indica en el enunciado.

P.D. Vuelvo a preguntar. Acepto su tarea en el repositorio con su usuario Unab? si no es así su tarea no sera revisada.

**Comment by Erick-Peralta** [comment]
Si la acepté, pero de momento no he hecho ningún commit todavía
