### ISSUE TITLE
2 cosas

### ISSUE THREAD

**Issue by ssozaprez** [INS125/Laboratorio#57]
1)Profe, ¿los nombres de los archivos de entrada y salida pueden ser cualquiera siempre que sean .in y .out? Me complica lo de filename que se repite varias veces y dónde abro los archivos y demás.

2)El fgets del código pre-hecho en matriz.c me manda error ("warning: inequality comparison result unused"). ¿Se debe utilizar en otra parte?

**Comment by Hormash** [comment]
1. R: Pueden tener cualquier formato, .txt, .csv, .in, etc. Pero tenga certeza que entre ellos tendrán un nombre distinto.

2. R: Que extraño, eso no debería sucedes. ¿Esta trabajando en un entorno Linux? Tal vez tiene algún carácter raro

**Comment by ssozaprez** [comment]
1. Oka. Gracias.

2. Estoy trabajando via consola en repl.it. No alteré ninguna parte del código pre-hecho en donde está el fgets. Lo único que he añadido hasta ahora ha sido el código para sumar pero no se si eso tendrá algo que ver ya que respeté los nombres de las variables y demás.

**Comment by ssozaprez** [comment]
Al dejar el fgets como un ciclo while (¿es eso válido hacer para la evaluación o cuenta como configurar un argumento?), me dejó de aparecer ese error. Ahora me aparece "undefined reference to LecturaMatriz" 3 veces.

**Comment by ssozaprez** [comment]
Okay, lo cloné de nuevo desde 0, lo compilé y ejectue, pero seguía apareciendo el mismo error. Al probar con el depurador, me salió lo siguiente:

Program received signal SIGSEGV, Segmentation fault.
_IO_fgets (buf=0x55b342c05060 <linea> "", n=5000, fp=0x0) at iofgets.c:47
47  iofgets.c: No such file or directory.

**Comment by Hormash** [comment]
https://github.com/INS125/Laboratorio/issues/51

**Comment by matgreco** [comment]
https://github.com/INS125/Laboratorio/issues/47

**Comment by ssozaprez** [comment]
Lo que me pasaba era que ponía -l 4 en en vez de -l 3 al momento de ejecutar por consola xd. Gracias.
