### ISSUE TITLE
Duda con archivos.out

### ISSUE THREAD

**Issue by lvp1890** [INS125/Laboratorio#58]
Hola profe, mi función de escritura crea uno solo de los archivos.out, en este caso el de suma y en vez de crear un conv.out crea un main que cuando trato de abrir me indica que no tienen contenido y no es posible abrir ese tipo de archivo. Creo que mi función esta bien ya que escribe el otro archivo, pero a qué se debe el error con el conv.out?

**Comment by Hormash** [comment]
Si esta creando un archivo main diria que no esta guardando correctamente el nombre del archivo en su código. 
Una duda acepto la tarea2 y creo el repositorio?

**Comment by lvp1890** [comment]
Si, tengo el repositorio que es tarea2-lvp1890 que es mi usuario. 
Respecto al nombre del archivo, en ningún momento lo declaro en el código, sino solamente con el comando por consola. Debería declararlo ? Porque nunca declare el de suma y funciona bien.

**Comment by lvp1890** [comment]
Lo revisé bien y era un error en mi función de convolución.
