### ISSUE TITLE
Error haciendo git push

### ISSUE THREAD

**Issue by JeanContreras12** [INS125/Laboratorio#59]
hice el push normalmente, previamente habia hecho uno y todo normal, ahora quise hacer otro y me arrojo el error "git error: failed to push some refs to remote", me sugeria hacer un "git pull --rebase"  por que aparentemente se estaba enviando otro push a la vez que el mio o algo asi entendi, luego hice un git rebase --continue y git rebase --skip, finalmente me dejo hacer el git push origin master y mi codigo se traspaso a mi repl privado, el problema es que al llegar venia con ediciones en el codigo como "<<<<<<< HEAD " y "=======" en todo el codigo, asi que pense que simplemente debia borrar esas cosas, pero ademas hay lineas de codigos que se repetian , y me arroja errores como que en " for(int i = 0; i < tamano; i++){ " espera un identificador o un ( , no se como arreglar esto.

**Comment by Hormash** [comment]
Te recomiendo que clones de nuevo el repositorio y hagas un commit limpio. Recuerda que el código debe estar limpio y correcto al momento de subir.

**Comment by JeanContreras12** [comment]
pero el codigo ya me quedo con los cambios al hacer ese commit, ahora siquiera me compila, como lo podria hacer para devolverlo a su estado previo?

**Comment by ssozaprez** [comment]
En tu repositorio, al dar click donde dice "commits" justo arriba de donde dice "Branch: master", puedes entonces dar click al último commit que hiciste y ver los cambios entre cómo estaba antes y ahora.
