### ISSUE TITLE
Errores por simbolos y largo de array

### ISSUE THREAD

**Issue by CristobalME96** [INS125/Laboratorio#6]
estoy teniendo un problema en los resultados, es un caso especifico causado por como funciona la separación de palabras. en el ejemplo 1 se consulta las veces que aparece Content, la cual aparece una vez, pero en los resultados me dice que aparece 0 veces debido a que la separación de palabras cuenta la palabra 'Content , para solucionar esto ¿es necesario hacer una limpieza de los simbolos que aparecen en el string?

el otro problema que tengo es que el array de int de largo 1000000 es demasiado grande para que el programa pueda compilar, lo logre compilar con un array de largo 510000, siendo este el maximo aproximado que le puedo dar antes de que deje de funcionar el programa

**Comment by matgreco** [comment]
Hola Cristobal,

No elimines símbolos, simplemente considera que los simbolos producen palabras distintas. "hola" tiene un hash distinto de "hola" y "content" de "content,". Eso está en el enunciado actualizado.

Podrías decirnos que error te aparece al declarar un arreglo de 1millon?. En teoría, no existe una dimensión máxima para declarar un error, pero en la práctica aveces tira segment fault cuando la memoria no dá. Muéstranos el error y vemos si se puede solucionar.

**Comment by CristobalME96** [comment]
ok, entonces si no tengo que eliminar simbolos creo que la salida del ejemplo 1 esta mal, porque dice que "Content" aparece una vez, pero no esta, si no que la palabra que aparece es " 'Content ".

efectivamente el error que me sale es el de segment fault, que imaginaba que podia ser por falta de memoria, tal vez una alternativa sea usar un hash de 500000 para que funcione.

**Comment by matgreco** [comment]
Excelente observación, gracias. Haremos una rev2 del enunciado y del ejemplo1.

Respecto al segmentation fault, eso es porque un arreglo reserva memoria en el segmento de memoria stack de manera continua, y probablemente tu equipo no tenga el espacio para 1millon de variables enteras continuas. Una solución rápida es reservando memoria en el segmento .bss declarando el arreglo como static.

´´´
static int arreglo[1000000];
´´´
Pero ojo, que eso deja tu variable visible en todos los ámbitos. Tendrá un comportamiento como variable global.

**Comment by CristobalME96** [comment]
con static logre solucionar el problema del arreglo, pero encontre otro problema de que el largo de lectura de 60 caracteres termina cortando palabras y para el ejemplo 2 cuenta revolutionary 3 veces, en vez de 5 como dice el ejemplo de salida, creo que esos son los unicos problemas que se presentan con la manera en que se lee el texto
