### ISSUE TITLE
Error al correr el programa en replit

### ISSUE THREAD

**Issue by Joaquin-Cortes** [INS125/Laboratorio#60]
hola profe tengo listo mi codigo y decidí probarlo en replit y a la hora de correr el programa me sale este error **"Segmentation fault (core dumped)"** y hice un debug y el error me salia en la funcion **lecturamatriz** en el **fgets (linea, 5000, fp) != NULL;**  y decia lo siguiente: 
Program received signal SIGSEGV, Segmentation fault.
_IO_fgets (buf=0x5646000eb060 <linea> "", n=5000, 
    fp=0x0) at iofgets.c:47
me parece raro porque en visual me corre sin ningún problema.
Saludos

**Comment by Hormash** [comment]
https://github.com/INS125/Laboratorio/issues/51

**Comment by Hormash** [comment]
https://github.com/INS125/Laboratorio/issues/47

**Comment by srecamang** [comment]
@Joaquin-Cortes pudiste solucionarlo, me sale el mismo error :(

**Comment by matgreco** [comment]
chicos, no se si vieron la #47 o #51, pero ese error lo han preguntado unas 20 veces, y es porque ponen el tamaño de la matriz -l 3 y la matriz de entrada es de tamaño 4. (o viceversa)

**Comment by srecamang** [comment]
profe mi matriz  es de 3x3 (ambas) y tengo el tamaño de matriz como 3 pero aun asi me tira el error.

**Comment by matgreco** [comment]
y con que parámetros ejecutas?

**Comment by Hormash** [comment]
Si su problema es distinto podría proporcionar más información de lo que esta haciendo.

- ¿Como estas compilando?
- ¿Como estas ejecutando?
- ¿Donde se encuentran los archivos de entrada?
- etc

**Comment by srecamang** [comment]
con estos parametros:
./main -a mUno.in  -b mDos.in -l 3 -f filG.in -s suma.out -c conv.out

**Comment by matgreco** [comment]
seguro que su matriz mUno.in y mDos.in son de tamaño 3??

seguro que el programa que compiló se llama "main" y no es un archivo compilado antes?

Seguro que la ruta de mUno y mDos es la misma que el programa que está ejecutando?

**Comment by Hormash** [comment]
No creo que eso sea de mucha ayuda para solucionar su problema...

**Comment by srecamang** [comment]
compilo asi : gcc main.c matriz.c -o main
ejecuto : ./main -a mUno.in  -b mDos.in -l 3 -f filG.in -s suma.out -c conv.out
los archivos de entrada los cree ahi el repl ( add files ->mUno.in , mDos.in, filG.in)

**Comment by srecamang** [comment]
gcc main.c matriz.c -o main
 ./main -a mUno.in  -b mDos.in -l 3 -f filG.in -s suma.out -c conv.out
Segmentation fault (core dumped)

**Comment by Hormash** [comment]
Puede indicar que muestra el comando 
`ls`
o el comando
`pwd`

**Comment by srecamang** [comment]
 ls
 filG.in   main.c     matriz.h  'mUno.in '
 main      matriz.c   mDos.in    README.md
 pwd
/home/runner/lab2/tarea2-srecamang

**Comment by Hormash** [comment]
y el contenido de estos archivos? por favor

**Comment by srecamang** [comment]
mUno.in : 
10;12;14
16;18;20
22;24;26

mDos.in:
2;3;4
5;6;7
8;9;10

filG.in:
0;1;0
1;0;1
0;1;0

**Comment by Hormash** [comment]
Me dice si puede ir a la siguiente sala
https://us.bbcollab.com/guest/80c781af052449e2bc650fb6bd2dffbe

**Comment by Hormash** [comment]
El problema era que el nombre del archivo mUno.in tenia un espacio al final 'mUno.in '
