### ISSUE TITLE
Error al Clonar

### ISSUE THREAD

**Issue by Erick-Peralta** [INS125/Laboratorio#63]
Cuando intento clonar mi repositorio me tira error sobre que falta un include stdin...

Python 3.8.2 (default, Feb 26 2020, 02:56:10)
 
 git clone https://github.com/INS125/tarea3-Erick-Peralta.git
  File "stdin", line 1
    git clone https://github.com/INS125/tarea3-Erick-Peralta.git
        ^
SyntaxError: invalid syntax

Como lo hago?

PD: Si lo clono poniendolo como Lenguaje C no me manda el error, pero si lo creo poniendo como lenguaje python me manda ese error.

**Comment by matgreco** [comment]
aqui puede encontrar las instrucciones para usar repl.it y python 

https://github.com/INS125/Laboratorio/blob/master/07/README.md

**Comment by Erick-Peralta** [comment]
> aqui puede encontrar las instrucciones para usar repl.it y python
> 
> https://github.com/INS125/Laboratorio/blob/master/07/README.md

Hola profe gracias por responder, finalmente pude clonar exitosamente mi repositorio, ahora me surgió la duda de como compilar? ya que al presionar el boton "Run" de la pagina me compila el main.py que se encuentra FUERA de la carpeta de mi repostorio, como hago para compilar el main.py que se encuentra DENTRO de mi repositorio y no la que viene por defecto? Muchas gracias

**Comment by m4rkhub** [comment]
Estimado Erick, si lo que quieres es ejecutar tu programa con "Run", debes copiar el contenido de tu archivo "main.py" del repo en el archivo "main.py" creado por repl (el que está vacío), tal como se indica en el documento en el paso 3.

**Comment by Erick-Peralta** [comment]
Muchas gracias, eso finalmente fue lo que hice pero pensé que debía ejercitarse únicamente dentro de la carpeta.

Solucionado, muchas gracias
