### ISSUE TITLE
Duda con generar csv

### ISSUE THREAD

**Issue by NaxF11** [INS125/Laboratorio#64]
Profe se hay generar y escribir un archivo csv mediante un for como lo hace en lectura (con yield)? O puedo hacerlo sin usar el yield?

**Comment by matgreco** [comment]
El yield no aplica ahi. 

Podría aplicar un map sobre la lista de salida, y una funcion que escriba linea a linea, una a una, sobre el archivo. Puede usar `join` para unir las partes de una lista con un ;

**Comment by katherin5928** [comment]
profe yo intente de poner

 archivo=open("salida.txt","w") 
  lis=';'.join(lista) 
  map(lambda escribir:archivo.write(lis),lista)
  archivo.close()

Pero tan solo me crea el archivo.Por otro lado le iba agregar lo de código sin embargo busque por Internet y no entiendo cual es mi error :(((

**Comment by katherin5928** [comment]
Profe yo lo intente pero tan solo me crea el archivo pero no me escribe :(((

**Comment by valeuwu** [comment]
profe a que se refiere con codigos en escribirArchivo??

**Comment by m4rkhub** [comment]
Era inicialmente el código de acceso a agregar en la lista, pero esa función ya no tiene restricción. Usted puede hacerla como desee.
PD: Recuerde que los nombres en los argumentos son sólo una idea.
