### ISSUE TITLE
desplazar z ¿?

### ISSUE THREAD

**Issue by frago3** [INS125/Laboratorio#65]
Hola, 

Se debe reemplazar los caracteres con tilde por sin tilde y ñ por n.
eso se debe hacer al concatenar el texto cierto? o al aplicar el cifrado inicial?

Concatenar el texto ='JonathanKreisberg'
Aplicar cifrado inicial = 'LqpcvjcpMtgkudgti'

Hay que remplazar digito verificador por 11 en caso de ser K.
¿en el texto de entrada K siempre va a estar en mayúscula?

Los caracteres especiales son los siguientes cierto?
[33, 34, 39, 40, 41, 42, 43, 44, 45, 46, 47, 58, 59, 60, 61, 62, 91, 92, 93, 94, 95, 96]
si encuentro un 33 que esta lista de caracteres especiales, entonces  33 +10 = 44
el 44 también esta en la lista. ¿debo sumar 10 al 44 cierto?

Si un nombre contiene la letra z, ¿Cómo se desplaza ese caracter?

**Comment by m4rkhub** [comment]
Hola!, voy por partes.
"Se debe reemplazar los caracteres con tilde por sin tilde y ñ por n.
eso se debe hacer al concatenar el texto cierto? o al aplicar el cifrado inicial?"
**R: Se debe hacer antes de aplicar el cifrado inicial.**

"Hay que remplazar digito verificador por 11 en caso de ser K.
¿en el texto de entrada K siempre va a estar en mayúscula?"
**R: Así es.**

"Los caracteres especiales son los siguientes cierto?
[33, 34, 39, 40, 41, 42, 43, 44, 45, 46, 47, 58, 59, 60, 61, 62, 91, 92, 93, 94, 95, 96]
si encuentro un 33 que esta lista de caracteres especiales, entonces 33 +10 = 44
el 44 también esta en la lista. ¿debo sumar 10 al 44 cierto?"
**R: Esto se debe corregir, dentro de la restricción de números menores a 33, deben cambiar esto por números menores a 35 y sumar ese mismo valor (35), y en la lista de caracteres especiales deben eliminar el 33, y el 34**

"Si un nombre contiene la letra z, ¿Cómo se desplaza ese caracter?"
**R: Si tienes la letra 'z' y la quieres desplazar una posición, el resultado sería 'a', al igual que si tienes la letra 'Z' y la desplazas una posición el resultado sería 'A'.**

**Comment by frago3** [comment]
R: Esto se debe corregir, dentro de la restricción de números menores a 33, deben cambiar esto por números menores a 35 y sumar ese mismo valor (35), y en la lista de caracteres especiales no considere el 33 ni el 34


Entonces eso cambia el código final de los usuarios, el info.csv del ejemplo estaría mal.

**Comment by m4rkhub** [comment]
En efecto, eso cambia el código final, pero no está mal, simplemente no se ha actualizado. La idea de esta modificación es que no tengan que revisar dos veces. De todas formas no necesita del archivo para continuar con su desarrollo. Actualizaré el archivo lo antes posible.

**Comment by m4rkhub** [comment]
Archivo actualizado.

**Comment by frago3** [comment]
creo que hay un error en el calculo del código validador, al parecer no se está multiplicando el dv con la suma del cifrado, en el info.csv digo

Antes de generar el código final debe calcular la operación señalada en el enunciado (operación validador())
Cifrado: ( 76113112991181069911277116103107117100103116105 )=[141]
Dígito verificador: ( 16.111.111-2 )=[2]
Resultado (141 * 2): 282
