### ISSUE TITLE
juntar nombre y apellido

### ISSUE THREAD

**Issue by katherin5928** [INS125/Laboratorio#66]
consulta profe porque si hago mi función con map y pongo:
 x:[x[0]+x[1] for x in x]

incluyendo con el lambda me escribe tan solo la primera las dos letras de cada una ejemplo así:
['ii', 'll', '99', '44']

y si lo hago con un filter sumando así x[0]+x[1]  me suma el primer nombre son el segundo nombre :((

la verdad e estado buscando por internet  pero no entiendo :((

**Comment by m4rkhub** [comment]
Hola!, recuerda que con map estás pasando por cada elemento de la lista si haces algo como:
map(lambda x: x, lista). También podrías usar map(lambda x: lista[x], range(len(lista))).

**Comment by katherin5928** [comment]
ahh...ya entendí gracias :)
