### ISSUE TITLE
Aclaraciones sobre los cambios

### ISSUE THREAD

**Issue by CristobalME96** [INS125/Laboratorio#68]
la funcion "escribirArchivo(lista,codigos)" la tenemos que eliminar del codigo original y luego crear una nueva funcion que utilizaremos para generar los archivos de salida?
En el enunciado se menciona que debemos implementar la funcion leerArchivo(nombrearchivo), esa deberia leer el archivo usuarios.csv? ya que eso se supone que lo hace la funcion que esta en lectura.py.
Por ultimo, los rut con guion 0 se opera como 0 o 10? ya que como 0 no parece ser util, en especial al generar el validador

**Comment by m4rkhub** [comment]
Hola! 
_"la funcion "escribirArchivo(lista,codigos)" la tenemos que eliminar del codigo original y luego crear una nueva funcion que utilizaremos para generar los archivos de salida?"_
**R: Así es, no tiene restricciones para crear dicha función. **

_"En el enunciado se menciona que debemos implementar la funcion leerArchivo(nombrearchivo), esa deberia leer el archivo usuarios.csv? ya que eso se supone que lo hace la funcion que esta en lectura.py." _
**R: Debe utilizar esa función para leer. **

_"Por ultimo, los rut con guion 0 se opera como 0 o 10? ya que como 0 no parece ser util, en especial al generar el validador"_
**R: Buena pregunta, no es muy eficiente con 0 pero es mejor que lo considere así, para evitar problemas con el resto de funciones. **
