### ISSUE TITLE
Duda con escrbir archivo

### ISSUE THREAD

**Issue by denilsonalx** [INS125/Laboratorio#69]
**Disulpen me pasa que estoy escribiendo los achivos csv, me crea los 2 pero solo me escribe en el primero que tenga el join, y el segundo lo deja en blanco, osea si pongo riesgocadena primero me escribe en riesgo y permitida la deja vacia, si escribo primero permitidacadena me escribe en permitdos y riesgo la deja vacia, alguna solucion para esto? :(**
riesgo = filter(Personasriesgo, usuarios)
riesgocadena = '\n'.join(';'.join(i) for i in riesgo)
escribirArchivoR(riesgocadena)

permitidos = filter(Personaspermitidas, usuarios)
permitidacadena = '\n'.join(';'.join(i) for i in permitidos)
escribirArchivoP(permitidacadena)

**Comment by m4rkhub** [comment]
Prueba volviendo a llamar al generador.
