### ISSUE TITLE
Consulta caracteres especiales ascii y sección de laboratorio

### ISSUE THREAD

**Issue by dzerene** [INS125/Laboratorio#7]
Hola profe, estaba probando el codigo ascii en c pero tengo un problema, solo puedo obtener hasta el valor 126 (siendo este "~") luego de este el programa me imprime los siguientes valores en blanco, si uso un scanf para preguntar especificamente por los valores que no se me entregan (como letras tildadas) me entrega el valor -61, ¿es necesario utilizar estos caracteres o es suficiente con los valores hasta el 126?
Mi otra consulta es sobre el problema con las secciones que más de algún alumno presenta, ya que algunos aún no podemos ser inscritos en el laboratorio, ¿tendremos algún problema por esto al momento de subir y revisar la tarea?
Muchas gracias por su tiempo

**Comment by matgreco** [comment]
Hola,
Es correcto. Los mayores a 126 corresponden a ascii extendido y en general no son imprimibles. Puedes revisar una tabla de codigos ascii para verificar la codificación https://elcodigoascii.com.ar/
si te entregan valores negativos es probable que estés usando algún tipo de dato incorrecto (como signed char), ya que los códigos ascii van de 0 a 256 (8bits - 1 byte), por lo que si usas una variable unsigned char debería mostrarte el código correcto. En  todo caso, la tarea se revisará con textos en ingles y se preguntará por palabras, pero estaría bueno que revisaras y nos contaras un poco mas como lo solucionaste.

Si no están inscritos, por ahora no hay problema. Obviamente deben subir su tarea al repositorio y crearla con el link que se envió. Si no está su nombre de usuario unab seleccione "Can’t find your name? Skip to the next step →"

Saludos.

**Comment by dzerene** [comment]
Efectivamente con unsigned char funcionó correctamente, más que nada me preocupaba el uso de letras tildadas, pero como los textos serán en inglés no hay problema, muchas gracias

**Comment by matgreco** [comment]
Excelente.

Respecto al otro tema ¿creaste tu repositorio con el link que se envió? Recuerda que es un repositorio distinta al de laboratorio0, este es el de Tarea1.

Te lo pregunto porque la separación por palabras ya venia incluido en el código base que se genera al crear el repositorio. 

Recuerda que la única forma de entregar la tarea es a través del repositorio.

Saludos.
