### ISSUE TITLE
Duda sobre marcas

### ISSUE THREAD

**Issue by bryanrodrguez** [INS125/Laboratorio#7]
Hola profe buenas noches , tengo una duda acerca el trabajo, en la clase usuario , la función marcar que hace?, muestra las marcas? O es el que añade las marcas al leer el archivo marcas.txt del usuario en especifico?

**Comment by Hormash** [comment]
Hola. El metodo marcar, es quien agrega las marcas al usuario. Por lo que cada usuario debería realizar sus marcas, es decir, desde el archivo de texto, cada usuario debería ya estar instanciado y agregar las marcas que le corresponden.
