### ISSUE TITLE
Ayuda para compilar lectura.py 

### ISSUE THREAD

**Issue by panchocorderos** [INS125/Laboratorio#70]
```py
def generadorArchivo(NombreArchivo):
    with open(NombreArchivo,'r') as f:
    	for line in f.readlines():
        	yield line.split("\n")[0].split(";") # esto elimina el caracter de salto de linea y lo separa por ;
```
Si al compilar este código, les muestra este error: 'UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 918: character maps to <undefined>' 

Tienen que agregarle al código anterior, el siguiente parámetro en **open**  _encoding='utf8'_ quedando así el código:
```py
def generadorArchivo(NombreArchivo):
    with open(NombreArchivo,'r', encoding='utf8') as f:
    	for line in f.readlines():
        	yield line.split("\n")[0].split(";") # esto elimina el caracter de salto de linea y lo separa por ;
```

**Comment by lordzen89** [comment]
Eso ocurre porque guardaste el archivo csv con codificación diferente a la que tiene tu sistema, intenta cambiarle la codificación al archivo por la que tenga tu SO. Si no puedes y no quieres perder tiempo, puedes parchar temporalmente agregando al open el argumento encoding="utf8" (quedaría así: with open(NombreArchivo,'r', encoding="utf8") as f:), mi archivo estaba en UTF-8 porque lo que hice fue tomarlo y descargar el raw directo del git.

**Comment by lordzen89** [comment]
Ojo ahí, esto va a generar problemas así que deberían estandarizar el encoding de los archivos que vayamos a entrega, ya que si el revisor tiene el archivo en ISO 8859-1 le dará el mismo error porque tú estás forzarndo a leerlo en UTF-8. @matgreco, podría señalarlos cuál será el encoding oficial para esta entrega?

**Comment by tomas-e** [comment]
@matgreco, podría señalarlos cuál será el encoding oficial para esta entrega?

**Comment by matgreco** [comment]
@m4rkhub debe indicar. A priori diría utf8

**Comment by m4rkhub** [comment]
Sí, utf8.
