### ISSUE TITLE
 Función generar archivo CSV

### ISSUE THREAD

**Issue by matixzz9** [INS125/Laboratorio#71]
Profe una pregunta, dado que en las actualizaciones de la tarea se eliminó la función para escribirArchivo y dado que en la Issue #64 nos dijeron al final del post que finalmente la función escribirArchivo  ya no tiene restricción y podíamos hacerla como nosotros deseamos.  ¿Se puede agregar entonces un for en la función para generar el archivo al igual que el for que viene por defecto en la función de lectura.py (línea 4)? Muchas gracias.

**Comment by m4rkhub** [comment]
Sí, puede hacerlo.
