### ISSUE TITLE
Uso de for

### ISSUE THREAD

**Issue by lordzen89** [INS125/Laboratorio#72]
Es posible usar for en este lab?  o debo usar map para todo?

**Comment by panchocorderos** [comment]
en el pdf del lab3 sale en el punto 4 _"Para desarrollar su solución deberá utilizar las funciones map, reduce y filter."_

**Comment by matgreco** [comment]
La restriccion es usar map, filter y reduce para todo.

Pero esta restriccion no corre para escribir archivo, como se aclaró en el issue #71

**Comment by frago3** [comment]
se puede usar ciclo for dentro de las todas funciones que vienen en el código base o solo en esa?

**Comment by panchocorderos** [comment]
Solo en la función escribir archivo
