### ISSUE TITLE
condicionales dentro de los ciclos map

### ISSUE THREAD

**Issue by katherin5928** [INS125/Laboratorio#73]
Consulta si los map son ciclos donde si uno la define por ejemplo map(lambda x.....,range(5))
provoca que  se haga 5 veces el ciclo.
 Como puedo poner una condicional en aquel ciclo en el cual si encuentra un dato en una lista me lo cambie por otro??.
Es que intente de poner un if e intente de hacerlo al igual que unos ejemplo de Internet sin embargo me dice que cierre la condicional y que antes de eso me ponga que pasara con aquella condicional si se llega a cumplir  pero sin el if. Otros me dicen que lo ponga después, sin embargo nada funciona.

Ahora bien como nada de eso me funciono intente de poner un filter sin embargo me retorna los valores  que deseo cambiar pero no me los cambia.

**Comment by katherin5928** [comment]
no ya no jaja pude solucionarlo atraves de poner la condicional sin igualarlo ejemplo ejemplo poner el numero asi:
1 if(largo[a]==2)else largo[a]

donde el 1 era el valor que se cambiaba en largo[a]

**Comment by m4rkhub** [comment]
Exacto!, para el condicional pones el "True" luego la condición y después el else.
