### ISSUE TITLE
Punto 6 del anexo. Caracteres especiales

### ISSUE THREAD

**Issue by tomas-e** [INS125/Laboratorio#74]
¿A que se refiere el punto 6 del anexo?

"6. Modificar caracteres especiales [’76’, ’56’, ’66’, ’57’, ’99’, ’56’, ’81’, ’51’, ’99’, ’56’,
’72’, ’71’, ’51’, ’55’, ’66’, ’52’, ’56’, ’71’, ’35’, ’55’, ’66’, ’51’, ’55’, ’52’]"

Se entiende por caracter especial todo aquel que no es letra ni número. En la funcion dice:
```
def modificarEspeciales(lista,especiales):
  #Recibe una lista de elementos pares y la lista con elementos especiales.
  #Retorna la lista con los elementos especiales modificados, si los hubiera.
  pass
```
¿Para qué una argumento con carácteres especiales si ya se sabe cuales son?
¿Se refiere a los caracteres que no le gustan al director?

De ser cierto esto último, ¿un caracter especial sería todo aquel que no es ni letra ni número y que además no le guste al director?

**Comment by m4rkhub** [comment]
Los caracteres especiales se refieren a la lista que está en el código base:
`especiales=[*range(39,48),*range(58,63),*range(91,97)]`
Entonces cuando llegas a ese punto, debes validar que ninguno de los caracteres de tu lista sea un miembro de la lista de caracteres especiales. En caso de encontrar uno debes tomar su valor y agregarle 10.

En el ejemplo en el punto 5 tienes lo siguiente:
['76', '46', '66', '47', '99', '46', '81', '41', '99', '46', '62', '71', '51', '45', '66', '42', '46', '71', '35', '45', '66', '51', '45', '52']

Si te fijas, el '46' está contenido en la lista de caracteres especiales, por lo tanto en el punto 6 su valor cambia a '56' (46+10).

['76', '56', '66', '57', '99', '56', '81', '51', '99', '56', '72', '71', '51', '55', '66', '52', '56', '71', '35', '55', '66', '51', '55', '52']

**Comment by lordzen89** [comment]
El 35 también es especial(#) pero no está en la lista, en el ejemplo, llegan 24 pares de caracteres, los cuales se transforman en 23 letras, donde no figura el 35 (a lo mejor el PDF se lo comió xD), el problema es que acá simplemente lo quita y no lo "convierte", por lo que si lo agrego a la lista de especiales, me va a cambiar el resultado del ejemplo... qué se haría en ese caso? Además, haciendo las pruebas tengo varios % y $, debo agregar sus valores a la tabla de especiales también?

Saludos o/

**Comment by m4rkhub** [comment]
No hay problema con el 35, la restricción es validar los menores a 35.

**Comment by lordzen89** [comment]
Me duda es porqué desapareció el # del código hasheado, ya que en el ejemplo del documento, este símbolo desaparece y no sale en resultado final.

**Comment by m4rkhub** [comment]
¿En qué parte lo ves desaparecer?

**Comment by lordzen89** [comment]
![image](https://user-images.githubusercontent.com/53202192/82846827-c5ec7300-9eb8-11ea-8877-5b2ae412530c.png)

El 35 es # y debería salir entre la G y el 7

**Comment by m4rkhub** [comment]
Estimado, excelente punto! pasa que en latex el caracter '#' es especial y debe ser escapado, como estaba dentro del código de acceso no me percaté de ese punto, por eso como ves en la imagen independiente de que en el código esté bien ingresado en el resultado del pdf no se ve. Lo corrijo asap. 
![evidencia-error-latex](https://user-images.githubusercontent.com/62608159/82908351-d7279500-9f35-11ea-9b71-a102813e459e.jpeg)

**Comment by m4rkhub** [comment]
Ahora debería estar ok.
![image](https://user-images.githubusercontent.com/62608159/82909429-4782e600-9f37-11ea-9ac5-80340c5fd16e.png)
