### ISSUE TITLE
error a pasar de string a entero

### ISSUE THREAD

**Issue by katherin5928** [INS125/Laboratorio#75]
Sabe que intente de pasar el ultimo dígito del rut a entero sin embargo cunado luego que hago la suma retorno la letra que debería darme.Sin embargo la suma en algunos caso me retorna como valores :

\x80' \x81  \x82

Ejemplo en el caso de:

ZsazsaBravo

['`', 'y', 'g', '\x80', 'y', 'g', 'H', 'x', 'g', '|', 'u']                             ESTE ES EL CIFRADO
[90, 115, 97, 122, 115, 97, 66, 114, 97, 118, 111]                  SIN EL VALOR 6 SOL ASCII
[96, 121, 103, 128, 121, 103, 72, 120, 103, 124, 117]            LA SUMA CON EL VALOR 6

Donde a cada letra le sumo 6 me entrega ese error :(((
A que se debe eso si transforme un string a entero.Ademas no me pasa eso con los valores 1 que ya son int.

pd: Estoy ocupando la transformación int('h') para transformarlo entero

**Comment by Hormash** [comment]
y la opción ord('h') le da problema?

**Comment by katherin5928** [comment]
no, no me da error con la opción ord('h')
