### ISSUE TITLE
Pregunta guardar informacion

### ISSUE THREAD

**Issue by Erick-Peralta** [INS125/Laboratorio#76]
Profe una pregunta, sucede que logro concatenar exitosamente  el nombre y el apellido tal y como se muestra en el ejemplo del pdf. Aqui hice como una "mini lista" para ir probandola, cosa de no agregar todos los elementos de una:

Esto es lo que me arroja en la consola:
(Imprimo mi mini lista)
[['Jonathan', 'Kreisberg', '19829285-2', '18-09-1956'], ['Probando', 'Erick', '10104619-4', '12-06-1977'], ['Sevilla', 'Probando', 20845823-1, '20-02-1993']]

(Concateno el nombre y el apellido)
JonathanKreisberg

(Extraigo el RUT)
19829285-2

(Guardo en una lista la cadena del NombreApellido + 2 de código ascii
['L', 'q', 'p', 'c', 'v', 'j', 'c', 'p', 'M', 't', 'g', 'k', 'u', 'd', 'g', 't', 'i']

(Convierto lo que está en la lista en una cadena)
LqpcvjcpMtgkudgti

(Transformo la cadena anterior en una lista aplicando el ord a cada letra/elemento de la lista anterior)

[76, 113, 112, 99, 118, 106, 99, 112, 77, 116, 103, 107, 117, 100, 103, 116, 105]

(La convierto en una cadena)
76113112991181069911277116103107117100103116105

Logro que me dé lo mismo que sale en el PDF. El problema que tengo es que para meter por ejemplo los numeros que me dieron en formato ascii ocupo 1 lista, si metiera al segundo usuario, sería otra lista.. y así consecutivamente, pero esa lista yo la defino en mi codigo como una lista vacía a=[] pero no puedo andar creando 4000000000 listas vacías para meter los numeros ascii de todos los usuarios, entonces no sé si guardar esa información en un tipo de matriz, o en una sola lista todos los numeros, pero como dice en el pdf es 1 lista para cada cadena de numeros, por lo que todos los usuarios deberían tener diferentes listas o no?

Si pusiera todo en una sola lista, me quedaria de esta forma:

[74, 111, 110, 97, 116, 104, 97, 110, 75, 114, 101, 105, 115, 98, 101, 114, 103, 109, 97, 100, 114, 105, 100, 101, 114, 105, 99, 107, 115, 101, 118, 105, 108, 108, 97, 97, 115, 100, 69, 114, 105, 99, 107, 80, 101, 114, 97, 108, 116, 97]

Pero de esta forma se me contradice el codigo hecho porque en 1 sola lista estarían todos los cifrados convertidos a enteros de todos los usuarios siendo que al parecer es una lista para cada cifrado.

Alguna sugerencia? Muchas gracias.

**Comment by m4rkhub** [comment]
No entiendo bien cómo llegaste a esa lista final, pero mira, cada uno de esos enteros que consigas (76113112991181069911277116103107117100103116105) corresponde a cada usuario. Por lo tanto lo puedes manejar como una lista, donde cada uno de los elementos corresponde a un usuario. Ejemplo: 

['76113112991181069911277116103107117100103116105', '791211181208611511910511497109114111105112', '831041101088398117107', '81114971201181146811011310697106', '671061151021091067798104115102111102', '8810810511211511410911512111981115114111', '69109978511911898111119117109122103', '70108991121051138410310711210699116102118', '8011711011689105117108111107114106', '7511910211511276102114103102113106'] , entonces 76113112991181069911277116103107117100103116105, es un elemento de esa lista, luego deberías separarlo por pares para formar la siguiente lista de elementos -> '76', '11', '31','12'...etc y continuar con lo que se solicita.
