### ISSUE TITLE
Consulta filtrar edad 

### ISSUE THREAD

**Issue by lvp1890** [INS125/Laboratorio#77]
Quiero usar filter() para filtrar la edad pero no comprendo como acceder a un elemento del arreglo. Por ejemplo si la lista es ['Juan', 'Ramos', '1234567-8','12-06-1977'], como puedo acceder a esa fecha? y una vez que la tengo como la comparo con la fecha dada, debo convertirla a entero o algo asi?

**Comment by m4rkhub** [comment]
Hola! revisa esta info https://github.com/INS125/Laboratorio/blob/master/08/test.py
