### ISSUE TITLE
consulta sobre lista usuarios

### ISSUE THREAD

**Issue by Joaquin-Cortes** [INS125/Laboratorio#78]
como no se pueden ocupar variables, a la hora de filtrar los mayores y menores a 01-01-1960, mi pregunta es si puedo separar en 2 variables, una lista de los mayores a esa fecha, y en otra los menores?

**Comment by m4rkhub** [comment]
No es necesario, además recuerde que cuando filtre a los mayores debe escribirlos en un archivo y no va a necesitar volver a utilizarlos.
