### ISSUE TITLE
consulta 

### ISSUE THREAD

**Issue by katherin5928** [INS125/Laboratorio#8]
profe recibí un archivo de texto en mi programa.sin embargo no se porque al momento de imprimir las palabras que ingresara en el texto no me los lee. Ejemplo

COMO LOS RECIBO DEL ARCHIVO DE TEXTO 

	for (s=0;s<numeroPalab;s++){
		fscanf(flujo,"%s",&arreglobus);
    
   
	}

COMO QUIERO ACCEDER A CADA PALABRA Y NO ME DEJA

	for (s=0;s<numeroPalab;s++){  //alamcena las palabras numero
		printf("%s",arreglobus[s]);
	}
	

no entiendo porque ocurre eso y no me deja acceder a cada palabra :(

**Comment by matgreco** [comment]
Hola Katherin,

Eso viene resuelto en el código base. En el código base se usa fgets en vez de fscanf.

Le recomiendo  cree su repositorio y utilice el código base en vez de programar su propio método.

**Comment by katherin5928** [comment]
Profe pero donde esta el código principal pues ingrese  a las carpetas y el único que me aparece es lo del lab 2 clase, las entrada y salidas nomas en la carpeta de tarea 1.

**Comment by matgreco** [comment]
@katherin5928 Debes crear tu repositorio con el link que se envió. 

Entra a tu blackboard, en "información general del curso" el tercer título dice "Tarea 1 Laboratorio". Hay está el link para crear el repositorio. Ojo que no es el mismo link ni el mismo repositorio que para el laboratorio0.

**Comment by katherin5928** [comment]
Profe sabe que no puedo acceder a cada elemento en especifico, ya que el código muestra la palabra por separado sin embargo no puedo acceder a un elemento especifico de un linea para utilizar .
intente de ponerla en un arreglo y sin embargo no me ingresar la palabra entera .
Ahora busque por Internet para guiarme y me sale con un scanf, esto me deja accede a una linea en especifico, sin embargo cuando ingrese a linea del texto me va a ocupar mas de una linea y en ese momento no me sirve. Por otro lado podría mezclar los dos pero no se como acceder a un elemento en especifico.

Por otro lado intente de acceder a linea[i], pero aun así no me deja me sale otra cosa nada que ver, para poder acceder a cada palabra.

La verdad no se que ya no se que otro método hacer  ya que e  hecho de todo para busca una solución, incluso  empece hacer el código antes pero sin el código base, y la verdad que se me agotan las ideas .

Para sacar incluso el numero ascii ya lo tengo hecho solo me falta acceder a los elementos de cada linea en especifico para seguir con mi desarrollo de mi programa.

Entonces no hay algún método que me deje acceder en un elemento en especifico 
@matgreco

**Comment by matgreco** [comment]
Hablemos hoy a las 14:00 en el lab. 

Creo que debes recordar que una cadena de caracteres es simplemente un arreglo de tipo char.
