### ISSUE TITLE
consulta digito verificador rut

### ISSUE THREAD

**Issue by lvp1890** [INS125/Laboratorio#81]
No entiendo como acceder al digito verificador del rut. Deberia hacerlo con un in-line for?
En el lab de preguntas de hoy se dio este ejemplo: list(map(lambda x:x.split("-")[1], funcion )), pero no me funciona, en la parte de funcion no entiendo lo que deberia colocar. Una vez que obtengo el digito debo convertirlo a entero para poder hacer la suma con las letras cierto?

**Comment by m4rkhub** [comment]
Depende de cómo estés revisando los elementos, puedes hacerlo con un map.
