### ISSUE TITLE
Escritura de archivo

### ISSUE THREAD

**Issue by lvp1890** [INS125/Laboratorio#82]
Consegui escribir el archivo pero usando el modulo de csv, es decir que hice el import hasta mientras para poder ir avanzando con el resto del codigo. Quisiera saber como puedo hcaerlo sin utilizar este modulo, Vi este ejemplo online pero no se cmo aplicarlo:
names = ["Lastname, Firstname", "Smith, John", "Bar, Foo"]
data = ','.join('"{0}"'.format(n) for n in names)
would yield a line like

"Lastname, Firstname","Smith, John","Bar, Foo"
en este caso names seria por ejemplo la lista de usuarios riesgo entonces es una lista de listas, entonces como lo puedo colocar en data? es permitido usar variables en esta parte?

**Comment by m4rkhub** [comment]
La función para escribir archivo ya no tiene restricción así que es libre para implementarla como guste. De todas formas le recomiendo no utilizar este módulo porque en el enunciado se establece que no se pueden utilizar más imports.
