### ISSUE TITLE
como puedo acceder una lista de lista

### ISSUE THREAD

**Issue by katherin5928** [INS125/Laboratorio#83]
profe consulta como puedo acceder a una lista de lista ejemplo:

list=[[12,32,65,48],[12,12,59],[45,87,22,57,69]]

como accedo a los valores de cada lista de cada persona es que sin los map se que con dos for pero con map no entiendo pues se que  lista [0] seria [12,32,65,48] pero no entiendo.

 Es que quier transformar los números pero no entiendo como hacerlo con map :(

**Comment by fluushx** [comment]
Hola compañera, te dejo un link que quizás te pueda ser de ayuda.
https://www.geeksforgeeks.org/python-map-function/

**Comment by katherin5928** [comment]
profe pero no entendí mucho pues ahí me muestra como hacer una lista de lista e intente de hacer lo inverso pero me muestra una lista pero de memoria nomas. y si paso mi map que tengo internamente a lista me sale error

**Comment by fluushx** [comment]
Mira te dejo otros videos explicativos donde quizas se pueda disipar un poco la duda
https://www.youtube.com/watch?v=hUes6y2b--0 
https://www.youtube.com/watch?v=cKlnR-CB3tk
ambos son en ingles

**Comment by fluushx** [comment]
https://github.com/INS125/Laboratorio/blob/master/07/lambda%20-%20map%20-%20filter%20-%20reduce.ipynb-

Tambien puedes revisar acá!

**Comment by katherin5928** [comment]
ya pude hacer pero lo pensé en el ámbito que fueran dos for gracias profe

**Comment by fluushx** [comment]
Ya señorita, pero no soy el profesor, soy un compañero! que tenga un buen día! :)

**Comment by katherin5928** [comment]
ya gracias
