### ISSUE TITLE
Consulta ejemplos

### ISSUE THREAD

**Issue by Camiloignaval** [INS125/Laboratorio#84]
Profe, el archivo info.csv, esta bien? particularmente el valor de la función validador, que hice dos a mano, y los dos me da lo mismo que hace mi programa, lo que difiere de los ejemplos, el que me coincide es el ejemplo que viene en el pdf si. quedo atento muchas gracias!

**Comment by fluushx** [comment]
El info.csv esta correcto por favor verificar la funcion validador, quizas algun metodo esta haciendo mal, tambien te recomiendo revisar el enunciado porque hace unos dias se actualizó.

**Comment by m4rkhub** [comment]
Camilo, me parece que está correcto, si encuentras que sigue habiendo un error lo podemos revisar.
