### ISSUE TITLE
Consulta sobre tildes y tipos de tildes

### ISSUE THREAD

**Issue by lordzen89** [INS125/Laboratorio#85]
La documentación señala: "También tenga en cuenta que los caracteres que tengan tildes deben ser reemplazados por su equivalente sin tilde (es decir, el carácter á debe ser reemplazado por a). "

Existen diferentes tipos de tilde áàä y en linux se pueden poner más cosillas, debo considerar que sólo existirá la tilde normal "á"?

Además se pueden tildar las consonantes (bendito linux), también deben ser consideradas?

Gracias o/

**Comment by fluushx** [comment]
En mi caso, yo solo consideré la tilde "normal" ya que cuando testie el documento "usuarios.csv" me resultó de esa manera, y no consideré las "àä"

**Comment by m4rkhub** [comment]
Exacto, sólo las tildes que vemos en español. No se compliquen con esos detalles.
