### ISSUE TITLE
función escribirArchivo

### ISSUE THREAD

**Issue by frago3** [INS125/Laboratorio#86]
veo ahora no se puede usar la función escribirArchivo que viene en el código base. ¿Hay que implementarla como lambda?

¿se puede usar la función generadorArchivo de lectura.py? si es así se puede modificar cierto? porque da error si no se le agrega la codificación utf-8

Saludos.

**Comment by m4rkhub** [comment]
No a todos les da error, pero entiendo que un compañero compartió una solución. Respecto a la función escribirArchivo en ninguna parte (creo) dice que no se puede usar, a lo que se hace referencia es que no tiene restricción, si quiere la utiliza como usted guste.

**Comment by frago3** [comment]
en el readme dice lo siguiente:

21-mayo: Se modifica la tercera restricción, ahora deberá evaluar valores menores a 35, y en caso de encontrarlos sumarles ese valor (35). **Además, se ha eliminado la función "escribirArchivo(lista,codigos)"**

Entonces no se elimina cierto?
Saludos

**Comment by m4rkhub** [comment]
Se refiere a que no tiene restricciones. Si quiera la utiliza. Saludos.
