### ISSUE TITLE
numero menores a 35

### ISSUE THREAD

**Issue by Joaquin-Cortes** [INS125/Laboratorio#87]
holaa mi duda es si es menor o menor o igual?

**Comment by m4rkhub** [comment]
Hola, menores a 35.

**Comment by Joaquin-Cortes** [comment]
otra pregunta es que si los codigos de acceso en info.csv  del ejemplo 1 estan actualizados?

**Comment by m4rkhub** [comment]
Deberían, ve algún error? Dígame para revisar.
