### ISSUE TITLE
tiempo de ejecución 

### ISSUE THREAD

**Issue by katherin5928** [INS125/Laboratorio#88]
profe consulta bajara nota por el tiempo de ejecución es  que provee mi programa con 3 persona y funciona perfecto asi full y hace todo. Sin embargo si lo hago con 200 se demora muuccchhhooo.

Por otro lado tengo una duda es que vi una actualizacion y salia eliminar función escribirArchivo por ende yo la elimine y escribí mi archivo en el main, eso no estaría mal cierto?

**Comment by m4rkhub** [comment]
No estaría mal, no se preocupe. De todas formas es curioso que se demore tanto con 200.

**Comment by matgreco** [comment]
yo diría que si estaría mal si toma mas tiempo del normal. Recordar que el revisor automático tendrá un tiempo de ejecución finito, por lo que si su programa no termina o demora demasiado, se detendrá la ejecución antes de que logre generar el archivo.

@m4rkhub podría darnos una breve tabla de referencia sobre cuanto tiempo demora su programa en resolver el problema, para tener una referencia. Recordar que esos tiempos de ejecución dependen de la máquina en la se ejecutan, sin embargo, nos dan luces sobre si su programa es correcto.

**Comment by katherin5928** [comment]
Es que la verdad  me funciona con 3 o 5 pero se demora mucho con lo demás y no se que hice mal entonces

**Comment by katherin5928** [comment]
Ademas me di cuenta que cuando tengo todo con variales se demora 17 segundos para  200 personas, cuando tengo tan solo variables en mi main pero en mis funciones no se demora 15 segundos con 200 personas  y cuando ya no hago no tengo ninguna variables mi programa esta todo el rato cargando mi programa sin parar
