### ISSUE TITLE
ejemplo 2, salida.txt

### ISSUE THREAD

**Issue by frago3** [INS125/Laboratorio#9]
hola,
Hay un dato en la salida.txt del ejemplo 2 que no me cuadra.
El hash de la palabra "revolutionary" me da 36323356819 lo que daría el siguinte hash:
36323356819 % 1000000 = 356819
en el archivo figura 618451

**Comment by matgreco** [comment]
Hola @frago3 

A mi el hash calculado para "revolutionary" con k=5 me da

 'revolutionary' 618451

que es el resto de la división entre 1963618451 %1000000

Podrías verificar tu cálculo en un excel con los códigos de cada letra??

**Comment by matgreco** [comment]
@frago3 mi cálculo tenia un error y es que desbordaba la el tamaño de un entero int.

Cambié a _unsigned long_ y me dio el resultado que decías tu 36323356819

Gracias! actualizaremos los ejemplos

**Comment by frago3** [comment]
oh gacias, yo por las dudas use el tipo de dato "long long"
