### ISSUE TITLE
Error al validar tildes

### ISSUE THREAD

**Issue by lvp1890** [INS125/Laboratorio#91]
SyntaxError: Non-ASCII character '\xc3' in file main.py on line 11, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

al utlizar esta linea : map(lambda x:x.replace("ñ","n"), listadepermitidos) 
ahi me sale ese error, como puedo arreglarlo?

**Comment by Hormash** [comment]
mmm, si intentas agregar encoding='utf-8' al momento de abrir el archivo de entrada te aparece ese error?

**Comment by Hormash** [comment]
Se soluciono agregando al inicio del código
`# coding=utf-8`
