### ISSUE TITLE
duda con respecto a las variables 

### ISSUE THREAD

**Issue by srecamang** [INS125/Laboratorio#92]
una duda, en el taller 3 no se puede crear ninguna variable de ningún tipo? es decir, todo mi código tiene que ser escrito en el return de las funciones dadas en el código base?
-- Mas tonto el que no pregunta...jaja
saludos

**Comment by Hormash** [comment]
Si puedes utilizar variables. 

`resultado = list(map(lambda x : x*2, range (0,5)))`

resultado es una nueva variable

**Comment by Hormash** [comment]
Se ha llegado a una nueva resolución y no se pueden utilizar variables.
