### ISSUE TITLE
Duda menores 35

### ISSUE THREAD

**Issue by lPipel** [INS125/Laboratorio#96]
Hola, profe en el ejemplo del lab el codigo cifrado luego de haber modificado los menores a 35 y luego de haber modificado los especiales, aparece que el cifrado es L8B9c8Q3c8HG37B48G7B374 como puede ver este contiene 23 caracteres. Pero si se fija en la lista del paso anterior, la cual tiene los valores ascii de cada letra de este cifrado, son 24 elementos. Faltando en este cifrado final (L8B9c8Q3c8HG37B48G7B374) el valor ascii 35, que se encuentra en la posición 18 en la lista con los ascii, y corresponderia al caracter "#". Este tendria que venir luego de la "G" y el cifrado final deberia verse asi "L8B9c8Q3c8HG37B48G#7B374". Esa es mi duda mas que nada, ya que mi programa me devuelve dicho cifrado final, y en el ejemplo no se ve. Tambien queria saber si es que el caracter "$" puede ser utilizado en el cifrado final. Ya que a un par de mis usuarios los cuales probe el codigo, en la lista de los ascii les quedaba el valor "36" el cual corresponde a este caracter, y este no se encuentra dentro de los especiales en el codigo.

**Comment by m4rkhub** [comment]
Hola estimado!, esto fue resuelto y está en el enunciado, te aconsejo veas el enunciado que está acá. 
Este issue fue revisado en #74. Respecto al caracter '$' no hay ningún problema.
