### ISSUE TITLE
Video para usar Git en Windows

### ISSUE THREAD

**Issue by panchocorderos** [INS125/Laboratorio#98]
Hola a todos! Adjunto un enlace para ver el mini tutorial que hice sobre git :)

https://us-lti.bbcollab.com/recording/2e6e301cb0a64310a0d6f1177372ab51

**Comment by valeuwu** [comment]
⭐ ⭐ ⭐ ⭐ ⭐  el tutorial, gracias pancho :D

**Comment by matgreco** [comment]
Gracias Pancho, tremendo aporte! Se va al root del repo.

**Comment by panchocorderos** [comment]
### Comandos útiles y/o frecuentes en Git:

`
git status // Comando que mostrará los diferentes estados de los archivos en tu directorio de trabajo y área de ensayo.
git add * // Comando para agregar todos los archivos modificados
git add <nombreArchivo> // Comando para agregar un archivo en especifico
git commit -m <stringTexto> // Comando que toma todos los contenidos de los archivos a los que se les realiza el seguimiento con **git add** y registra una nueva instantánea permanente en la base de datos y luego avanza el puntero de la rama en la rama actual.
git push origin master  // Comando que empuja las confirmaciones en la rama local llamada **Master** al remoto(repositorio) llamado **Origin**
` 

Si quieren investigar mas comandos, acá les dejo un link con la documentación!
https://git-scm.com/book/es/v2/Appendix-B%3A-Comandos-de-Git-Seguimiento-B%C3%A1sico
