### ISSUE TITLE
Declaración de conexión  

### ISSUE THREAD

**Issue by Deivid45-droid** [INS125/Laboratorio#99]
Es necesario declarar 2 veces si (0,0) conecta con (1,0)  y viceversa declarar  (0.0)(1.0) y luego (1.0)(0.0)? porque siendo así al buscar el camino no se detiene solo sigue recorriendo ,en cambio si es de una sola dirección  entrega el camino.

**Comment by matgreco** [comment]
Hola Deivid. 

Eso lo puede definir usted. Sin embargo, lo que si es necesario es poder determinar que (utilizando su propio ejemplo) una acción posible del estado nodo(1,0) es ir hacia el nodo(0,0). 

Si en sus reglas, sus conexiones son bidireccionales, puede declararla una sola vez. Sin embargo, si sus reglas son unidireccionales debería hacer lo que dice
